//! API layer

pub mod v1;

// Legacy modules (deprecated, will be removed in v2)
pub mod auth;
pub mod users;

// Explicit re-exports to avoid ambiguity
pub use auth::configure as auth_configure;
pub use users::configure as users_configure;

// V1 re-exports
pub use v1::accounting_configure as v1_accounting_configure;
pub use v1::api_keys_configure as v1_api_keys_configure;
pub use v1::archive_configure as v1_archive_configure;
pub use v1::assets_configure as v1_assets_configure;
pub use v1::audit_configure as v1_audit_configure;
pub use v1::auth_configure as v1_auth_configure;
pub use v1::bank_configure as v1_bank_configure;
pub use v1::barcode_configure as v1_barcode_configure;
pub use v1::cari_configure as v1_cari_configure;
pub use v1::chart_of_accounts_configure as v1_chart_of_accounts_configure;
pub use v1::companies_configure as v1_companies_configure;
pub use v1::cost_centers_configure as v1_cost_centers_configure;
pub use v1::crm_configure as v1_crm_configure;
pub use v1::currency_configure as v1_currency_configure;
pub use v1::custom_fields_configure as v1_custom_fields_configure;
pub use v1::customer_portal_configure as v1_customer_portal_configure;
pub use v1::dashboard_configure as v1_dashboard_configure;
pub use v1::documents_configure as v1_documents_configure;
pub use v1::earchive_configure as v1_earchive_configure;
pub use v1::edefter_blockchain_configure as v1_edefter_blockchain_configure;
pub use v1::edefter_configure as v1_edefter_configure;
pub use v1::efatura_configure as v1_efatura_configure;
pub use v1::events_configure as v1_events_configure;
pub use v1::feature_flags_configure as v1_feature_flags_configure;
pub use v1::files_configure as v1_files_configure;
pub use v1::forecasting_configure as v1_forecasting_configure;
pub use v1::goods_receipts_configure as v1_goods_receipts_configure;
pub use v1::graphql_configure as v1_graphql_configure;
pub use v1::hr_configure as v1_hr_configure;
pub use v1::import_configure as v1_import_configure;
pub use v1::invoice_configure as v1_invoice_configure;
pub use v1::ip_whitelist_configure as v1_ip_whitelist_configure;
pub use v1::jobs_configure as v1_jobs_configure;
pub use v1::ldap_configure as v1_ldap_configure;
pub use v1::manufacturing_configure as v1_manufacturing_configure;
pub use v1::mfa_configure as v1_mfa_configure;
pub use v1::notifications_configure as v1_notifications_configure;
pub use v1::observability_configure as v1_observability_configure;
pub use v1::product_variants_configure as v1_product_variants_configure;
pub use v1::project_configure as v1_project_configure;
pub use v1::purchase_orders_configure as v1_purchase_orders_configure;
pub use v1::purchase_requests_configure as v1_purchase_requests_configure;
pub use v1::push_notifications_configure as v1_push_notifications_configure;
pub use v1::rate_limits_configure as v1_rate_limits_configure;
pub use v1::reports_configure as v1_reports_configure;
pub use v1::resilience_configure as v1_resilience_configure;
pub use v1::sales_configure as v1_sales_configure;
pub use v1::search_configure as v1_search_configure;
pub use v1::settings_configure as v1_settings_configure;
pub use v1::shifts_configure as v1_shifts_configure;
pub use v1::stock_configure as v1_stock_configure;
pub use v1::subscriptions_configure as v1_subscriptions_configure;
pub use v1::tax_configure as v1_tax_configure;
pub use v1::tenant_configure as v1_tenant_configure;
pub use v1::users_configure as v1_users_configure;
pub use v1::vendor_portal_configure as v1_vendor_portal_configure;
pub use v1::webhooks_configure as v1_webhooks_configure;
pub use v1::workflows_configure as v1_workflows_configure;

use crate::common::MessageResponse;
use crate::domain::auth::{LoginRequest, LoginResponse, RefreshTokenRequest, RegisterRequest};
use crate::domain::feature::{
    CreateFeatureFlag, FeatureFlagResponse, FeatureFlagStatus, UpdateFeatureFlag,
};
use crate::domain::user::{CreateUser, UpdateUser, UserResponse};
use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::Modify;
use utoipa::OpenApi;

/// OpenAPI specification for the Turerp ERP API
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Turerp ERP API",
        description = "Multi-tenant SaaS ERP system API\n\n## Authentication\n\nAll endpoints except `/api/v1/auth/login`, `/api/v1/auth/register`, and `/api/v1/auth/refresh` require JWT Bearer token authentication.\n\n## Rate Limiting\n\nAuthentication endpoints are rate limited to 10 requests per minute per IP address with a burst of 3 requests.\n\n## Localization\n\nAll endpoints support per-request localization via the `Accept-Language` header. Supported languages: `en` (default), `tr`.\n\n## API Versioning\n\n- `/api/v1/` - Current stable API (recommended)\n- `/api/auth/`, `/api/users/` - Legacy routes (deprecated, will be removed in v2)",
        version = "1.0.0",
        contact(
            name = "Turerp Team",
            email = "info@turerp.com"
        )
    ),
    paths(
        // Auth
        crate::api::v1::auth::register,
        crate::api::v1::auth::login,
        crate::api::v1::auth::refresh_token,
        crate::api::v1::auth::me,
        // MFA
        crate::api::v1::mfa::mfa_setup,
        crate::api::v1::mfa::mfa_verify_setup,
        crate::api::v1::mfa::mfa_disable,
        crate::api::v1::mfa::mfa_status,
        crate::api::v1::mfa::mfa_verify,
        crate::api::v1::mfa::mfa_regenerate_backup_codes,
        // Bank
        crate::api::v1::bank::create_account,
        crate::api::v1::bank::get_accounts,
        crate::api::v1::bank::get_account,
        crate::api::v1::bank::update_account,
        crate::api::v1::bank::delete_account,
        crate::api::v1::bank::restore_account,
        crate::api::v1::bank::destroy_account,
        crate::api::v1::bank::upload_statement,
        crate::api::v1::bank::get_transactions,
        crate::api::v1::bank::get_unmatched_transactions,
        crate::api::v1::bank::match_transaction,
        crate::api::v1::bank::unmatch_transaction,
        crate::api::v1::bank::get_reconciliation_report,
        crate::api::v1::bank::auto_reconcile,
        crate::api::v1::bank::create_rule,
        crate::api::v1::bank::get_rules,
        crate::api::v1::bank::get_rule,
        crate::api::v1::bank::update_rule,
        crate::api::v1::bank::delete_rule,
        // Barcodes
        crate::api::v1::barcode::generate_barcode,
        crate::api::v1::barcode::get_barcode_for_entity,
        crate::api::v1::barcode::delete_barcode,
        crate::api::v1::barcode::list_barcodes,
        // Users
        crate::api::v1::users::create_user,
        crate::api::v1::users::get_user,
        crate::api::v1::users::get_users,
        crate::api::v1::users::update_user,
        crate::api::v1::users::delete_user,
        crate::api::v1::users::restore_user,
        crate::api::v1::users::list_deleted_users,
        crate::api::v1::users::destroy_user,
        // LDAP
        crate::api::v1::ldap::create_ldap_config,
        crate::api::v1::ldap::get_ldap_config,
        crate::api::v1::ldap::update_ldap_config,
        crate::api::v1::ldap::delete_ldap_config,
        crate::api::v1::ldap::test_ldap_connection,
        crate::api::v1::ldap::sync_ldap_users,
        // Webhooks
        crate::api::v1::webhooks::create_webhook,
        crate::api::v1::webhooks::list_webhooks,
        crate::api::v1::webhooks::get_webhook,
        crate::api::v1::webhooks::update_webhook,
        crate::api::v1::webhooks::delete_webhook,
        crate::api::v1::webhooks::restore_webhook,
        crate::api::v1::webhooks::list_deleted_webhooks,
        crate::api::v1::webhooks::destroy_webhook,
        crate::api::v1::webhooks::test_webhook,
        crate::api::v1::webhooks::list_deliveries,
        crate::api::v1::webhooks::retry_delivery,
        // Tenant
        crate::api::v1::tenant::create_tenant,
        crate::api::v1::tenant::get_tenants,
        crate::api::v1::tenant::get_tenant,
        crate::api::v1::tenant::update_tenant,
        crate::api::v1::tenant::delete_tenant,
        crate::api::v1::tenant::restore_tenant,
        crate::api::v1::tenant::list_deleted_tenants,
        crate::api::v1::tenant::destroy_tenant,
        crate::api::v1::tenant::create_tenant_config,
        crate::api::v1::tenant::get_tenant_configs,
        crate::api::v1::tenant::get_tenant_config,
        crate::api::v1::tenant::update_tenant_config,
        crate::api::v1::tenant::delete_tenant_config,
        // Cari
        crate::api::v1::cari::create_cari,
        crate::api::v1::cari::get_cari,
        crate::api::v1::cari::get_all_cari,
        crate::api::v1::cari::get_cari_by_type,
        crate::api::v1::cari::search_cari,
        crate::api::v1::cari::update_cari,
        crate::api::v1::cari::delete_cari,
        crate::api::v1::cari::restore_cari,
        crate::api::v1::cari::list_deleted_cari,
        crate::api::v1::cari::destroy_cari,
        // Stock
        crate::api::v1::stock::create_warehouse,
        crate::api::v1::stock::get_warehouses,
        crate::api::v1::stock::get_warehouse,
        crate::api::v1::stock::update_warehouse,
        crate::api::v1::stock::delete_warehouse,
        crate::api::v1::stock::restore_warehouse,
        crate::api::v1::stock::list_deleted_warehouses,
        crate::api::v1::stock::destroy_warehouse,
        crate::api::v1::stock::create_stock_movement,
        crate::api::v1::stock::get_stock_movements_by_product,
        crate::api::v1::stock::get_stock_movements_by_warehouse,
        crate::api::v1::stock::restore_stock_movement,
        crate::api::v1::stock::list_deleted_stock_movements,
        crate::api::v1::stock::destroy_stock_movement,
        crate::api::v1::stock::get_stock_by_product,
        crate::api::v1::stock::get_stock_by_warehouse,
        crate::api::v1::stock::restore_stock_level,
        crate::api::v1::stock::list_deleted_stock_levels,
        crate::api::v1::stock::destroy_stock_level,
        crate::api::v1::stock::get_stock_summary,
        // Invoice
        crate::api::v1::invoice::create_invoice,
        crate::api::v1::invoice::get_invoice,
        crate::api::v1::invoice::get_invoices,
        crate::api::v1::invoice::get_invoices_by_status,
        crate::api::v1::invoice::get_outstanding_invoices,
        crate::api::v1::invoice::get_overdue_invoices,
        crate::api::v1::invoice::update_invoice_status,
        crate::api::v1::invoice::delete_invoice,
        crate::api::v1::invoice::restore_invoice,
        crate::api::v1::invoice::list_deleted_invoices,
        crate::api::v1::invoice::destroy_invoice,
        crate::api::v1::invoice::create_payment,
        crate::api::v1::invoice::get_payments_by_invoice,
        // Sales
        crate::api::v1::sales::create_sales_order,
        crate::api::v1::sales::get_sales_orders,
        crate::api::v1::sales::get_sales_order,
        crate::api::v1::sales::get_sales_orders_by_status,
        crate::api::v1::sales::update_sales_order_status,
        crate::api::v1::sales::delete_sales_order,
        crate::api::v1::sales::restore_sales_order,
        crate::api::v1::sales::list_deleted_sales_orders,
        crate::api::v1::sales::destroy_sales_order,
        crate::api::v1::sales::create_quotation,
        crate::api::v1::sales::get_quotations,
        crate::api::v1::sales::get_quotation,
        crate::api::v1::sales::get_quotations_by_status,
        crate::api::v1::sales::update_quotation_status,
        crate::api::v1::sales::convert_quotation_to_order,
        crate::api::v1::sales::delete_quotation,
        crate::api::v1::sales::restore_quotation,
        crate::api::v1::sales::list_deleted_quotations,
        crate::api::v1::sales::destroy_quotation,
        // Purchase Orders
        crate::api::v1::purchase_orders::create_order,
        crate::api::v1::purchase_orders::get_orders,
        crate::api::v1::purchase_orders::get_order,
        crate::api::v1::purchase_orders::update_order_status,
        crate::api::v1::purchase_orders::delete_order,
        crate::api::v1::purchase_orders::restore_order,
        crate::api::v1::purchase_orders::list_deleted_orders,
        crate::api::v1::purchase_orders::destroy_order,
        // Purchase Requests
        crate::api::v1::purchase_requests::create_request,
        crate::api::v1::purchase_requests::get_requests,
        crate::api::v1::purchase_requests::get_request,
        crate::api::v1::purchase_requests::update_request,
        crate::api::v1::purchase_requests::submit_request,
        crate::api::v1::purchase_requests::approve_request,
        crate::api::v1::purchase_requests::reject_request,
        crate::api::v1::purchase_requests::delete_request,
        crate::api::v1::purchase_requests::restore_request,
        crate::api::v1::purchase_requests::list_deleted_requests,
        crate::api::v1::purchase_requests::destroy_request,
        // Rate Limits
        crate::api::v1::rate_limits::get_rate_limit_stats,
        // Goods Receipts
        crate::api::v1::goods_receipts::create_receipt,
        crate::api::v1::goods_receipts::get_receipt,
        crate::api::v1::goods_receipts::get_receipts_by_order,
        crate::api::v1::goods_receipts::update_receipt_status,
        crate::api::v1::goods_receipts::delete_receipt,
        crate::api::v1::goods_receipts::restore_receipt,
        crate::api::v1::goods_receipts::list_deleted_receipts,
        crate::api::v1::goods_receipts::destroy_receipt,
        // HR
        crate::api::v1::hr::employees::create_employee,
        crate::api::v1::hr::employees::get_employees,
        crate::api::v1::hr::employees::get_employee,
        crate::api::v1::hr::employees::update_employee_status,
        crate::api::v1::hr::employees::terminate_employee,
        crate::api::v1::hr::employees::soft_delete_employee,
        crate::api::v1::hr::employees::restore_employee,
        crate::api::v1::hr::employees::list_deleted_employees,
        crate::api::v1::hr::employees::destroy_employee,
        crate::api::v1::hr::attendance::record_attendance,
        crate::api::v1::hr::attendance::get_attendance_by_employee,
        crate::api::v1::hr::attendance::soft_delete_attendance,
        crate::api::v1::hr::attendance::restore_attendance,
        crate::api::v1::hr::attendance::list_deleted_attendance,
        crate::api::v1::hr::attendance::destroy_attendance,
        crate::api::v1::hr::leave::create_leave_request,
        crate::api::v1::hr::leave::get_leave_requests_by_employee,
        crate::api::v1::hr::leave::approve_leave_request,
        crate::api::v1::hr::leave::reject_leave_request,
        crate::api::v1::hr::leave::soft_delete_leave_request,
        crate::api::v1::hr::leave::restore_leave_request,
        crate::api::v1::hr::leave::list_deleted_leave_requests,
        crate::api::v1::hr::leave::destroy_leave_request,
        crate::api::v1::hr::leave::get_leave_types,
        crate::api::v1::hr::leave::soft_delete_leave_type,
        crate::api::v1::hr::leave::restore_leave_type,
        crate::api::v1::hr::leave::list_deleted_leave_types,
        crate::api::v1::hr::leave::destroy_leave_type,
        crate::api::v1::hr::payroll::calculate_payroll,
        crate::api::v1::hr::payroll::get_payroll_by_employee,
        crate::api::v1::hr::payroll::mark_payroll_paid,
        crate::api::v1::hr::payroll::soft_delete_payroll,
        crate::api::v1::hr::payroll::restore_payroll,
        crate::api::v1::hr::payroll::list_deleted_payroll,
        crate::api::v1::hr::payroll::destroy_payroll,
        // Accounting
        crate::api::v1::accounting::create_account,
        crate::api::v1::accounting::get_accounts,
        crate::api::v1::accounting::get_accounts_by_type,
        crate::api::v1::accounting::get_account,
        crate::api::v1::accounting::soft_delete_account,
        crate::api::v1::accounting::restore_account,
        crate::api::v1::accounting::list_deleted_accounts,
        crate::api::v1::accounting::destroy_account,
        crate::api::v1::accounting::create_journal_entry,
        crate::api::v1::accounting::get_journal_entries,
        crate::api::v1::accounting::get_journal_entry,
        crate::api::v1::accounting::post_journal_entry,
        crate::api::v1::accounting::void_journal_entry,
        crate::api::v1::accounting::soft_delete_journal_entry,
        crate::api::v1::accounting::restore_journal_entry,
        crate::api::v1::accounting::list_deleted_journal_entries,
        crate::api::v1::accounting::destroy_journal_entry,
        crate::api::v1::accounting::generate_trial_balance,
        // Assets
        crate::api::v1::assets::create_asset,
        crate::api::v1::assets::get_assets,
        crate::api::v1::assets::get_asset,
        crate::api::v1::assets::get_assets_by_status,
        crate::api::v1::assets::update_asset,
        crate::api::v1::assets::update_asset_status,
        crate::api::v1::assets::calculate_depreciation,
        crate::api::v1::assets::record_depreciation,
        crate::api::v1::assets::dispose_asset,
        crate::api::v1::assets::write_off_asset,
        crate::api::v1::assets::start_maintenance,
        crate::api::v1::assets::end_maintenance,
        crate::api::v1::assets::soft_delete_asset,
        crate::api::v1::assets::restore_asset,
        crate::api::v1::assets::list_deleted_assets,
        crate::api::v1::assets::destroy_asset,
        crate::api::v1::assets::create_maintenance_record,
        crate::api::v1::assets::get_maintenance_records,
        // Project
        crate::api::v1::project::create_project,
        crate::api::v1::project::get_projects,
        crate::api::v1::project::get_project,
        crate::api::v1::project::update_project_status,
        crate::api::v1::project::soft_delete_project,
        crate::api::v1::project::restore_project,
        crate::api::v1::project::list_deleted_projects,
        crate::api::v1::project::destroy_project,
        crate::api::v1::project::create_wbs_item,
        crate::api::v1::project::get_wbs_by_project,
        crate::api::v1::project::update_wbs_progress,
        crate::api::v1::project::create_project_cost,
        crate::api::v1::project::get_project_costs,
        crate::api::v1::project::get_profitability,
        // Manufacturing
        crate::api::v1::manufacturing::work_orders::create_work_order,
        crate::api::v1::manufacturing::work_orders::get_work_orders,
        crate::api::v1::manufacturing::work_orders::get_work_order,
        crate::api::v1::manufacturing::work_orders::update_work_order_status,
        crate::api::v1::manufacturing::work_orders::soft_delete_work_order,
        crate::api::v1::manufacturing::work_orders::restore_work_order,
        crate::api::v1::manufacturing::work_orders::list_deleted_work_orders,
        crate::api::v1::manufacturing::work_orders::destroy_work_order,
        crate::api::v1::manufacturing::work_orders::add_work_order_operation,
        crate::api::v1::manufacturing::work_orders::get_work_order_operations,
        crate::api::v1::manufacturing::work_orders::add_work_order_material,
        crate::api::v1::manufacturing::work_orders::get_work_order_materials,
        crate::api::v1::manufacturing::boms::create_bom,
        crate::api::v1::manufacturing::boms::get_bom,
        crate::api::v1::manufacturing::boms::get_boms_by_product,
        crate::api::v1::manufacturing::boms::add_bom_line,
        crate::api::v1::manufacturing::boms::get_bom_lines,
        crate::api::v1::manufacturing::boms::soft_delete_bom,
        crate::api::v1::manufacturing::boms::restore_bom,
        crate::api::v1::manufacturing::boms::list_deleted_boms,
        crate::api::v1::manufacturing::boms::destroy_bom,
        crate::api::v1::manufacturing::routings::create_routing,
        crate::api::v1::manufacturing::routings::get_routing,
        crate::api::v1::manufacturing::routings::get_routings_by_product,
        crate::api::v1::manufacturing::routings::add_routing_operation,
        crate::api::v1::manufacturing::routings::soft_delete_routing,
        crate::api::v1::manufacturing::routings::restore_routing,
        crate::api::v1::manufacturing::routings::list_deleted_routings,
        crate::api::v1::manufacturing::routings::destroy_routing,
        crate::api::v1::manufacturing::routings::calculate_material_requirements,
        crate::api::v1::manufacturing::quality_control::create_inspection,
        crate::api::v1::manufacturing::quality_control::get_inspections,
        crate::api::v1::manufacturing::quality_control::get_inspection,
        crate::api::v1::manufacturing::quality_control::update_inspection,
        crate::api::v1::manufacturing::quality_control::delete_inspection,
        crate::api::v1::manufacturing::quality_control::restore_inspection,
        crate::api::v1::manufacturing::quality_control::list_deleted_inspections,
        crate::api::v1::manufacturing::quality_control::destroy_inspection,
        crate::api::v1::manufacturing::quality_control::create_ncr,
        crate::api::v1::manufacturing::quality_control::get_ncrs,
        crate::api::v1::manufacturing::quality_control::get_ncr,
        crate::api::v1::manufacturing::quality_control::update_ncr,
        crate::api::v1::manufacturing::quality_control::delete_ncr,
        crate::api::v1::manufacturing::quality_control::restore_ncr,
        crate::api::v1::manufacturing::quality_control::list_deleted_ncrs,
        crate::api::v1::manufacturing::quality_control::destroy_ncr,
        // CRM
        crate::api::v1::crm::leads::create_lead,
        crate::api::v1::crm::leads::get_leads,
        crate::api::v1::crm::leads::get_lead,
        crate::api::v1::crm::leads::get_leads_by_status,
        crate::api::v1::crm::leads::update_lead_status,
        crate::api::v1::crm::leads::soft_delete_lead,
        crate::api::v1::crm::leads::restore_lead,
        crate::api::v1::crm::leads::list_deleted_leads,
        crate::api::v1::crm::leads::destroy_lead,
        crate::api::v1::crm::leads::convert_lead,
        crate::api::v1::crm::opportunities::create_opportunity,
        crate::api::v1::crm::opportunities::get_opportunities,
        crate::api::v1::crm::opportunities::get_opportunity,
        crate::api::v1::crm::opportunities::get_opportunities_by_status,
        crate::api::v1::crm::opportunities::update_opportunity_status,
        crate::api::v1::crm::opportunities::soft_delete_opportunity,
        crate::api::v1::crm::opportunities::restore_opportunity,
        crate::api::v1::crm::opportunities::list_deleted_opportunities,
        crate::api::v1::crm::opportunities::destroy_opportunity,
        crate::api::v1::crm::opportunities::get_pipeline_value,
        crate::api::v1::crm::campaigns::create_campaign,
        crate::api::v1::crm::campaigns::get_campaigns,
        crate::api::v1::crm::campaigns::get_campaign,
        crate::api::v1::crm::campaigns::get_campaigns_by_status,
        crate::api::v1::crm::campaigns::update_campaign_status,
        crate::api::v1::crm::campaigns::soft_delete_campaign,
        crate::api::v1::crm::campaigns::restore_campaign,
        crate::api::v1::crm::campaigns::list_deleted_campaigns,
        crate::api::v1::crm::campaigns::destroy_campaign,
        crate::api::v1::crm::tickets::create_ticket,
        crate::api::v1::crm::tickets::get_tickets,
        crate::api::v1::crm::tickets::get_ticket,
        crate::api::v1::crm::tickets::get_tickets_by_status,
        crate::api::v1::crm::tickets::update_ticket_status,
        crate::api::v1::crm::tickets::soft_delete_ticket,
        crate::api::v1::crm::tickets::restore_ticket,
        crate::api::v1::crm::tickets::list_deleted_tickets,
        crate::api::v1::crm::tickets::destroy_ticket,
        crate::api::v1::crm::tickets::resolve_ticket,
        crate::api::v1::crm::tickets::get_open_tickets_count,
        // Chart of Accounts
        crate::api::v1::chart_of_accounts::create_chart_account,
        crate::api::v1::chart_of_accounts::list_chart_accounts,
        crate::api::v1::chart_of_accounts::get_chart_account_by_code,
        crate::api::v1::chart_of_accounts::update_chart_account,
        crate::api::v1::chart_of_accounts::soft_delete_chart_account,
        crate::api::v1::chart_of_accounts::restore_chart_account,
        crate::api::v1::chart_of_accounts::list_deleted_chart_accounts,
        crate::api::v1::chart_of_accounts::destroy_chart_account,
        crate::api::v1::chart_of_accounts::get_account_tree,
        crate::api::v1::chart_of_accounts::get_chart_account_children,
        crate::api::v1::chart_of_accounts::recalculate_chart_account_balance,
        crate::api::v1::chart_of_accounts::get_trial_balance,
        // Cost Centers
        crate::api::v1::cost_centers::create_cost_center,
        crate::api::v1::cost_centers::list_cost_centers,
        crate::api::v1::cost_centers::get_cost_center,
        crate::api::v1::cost_centers::update_cost_center,
        crate::api::v1::cost_centers::delete_cost_center,
        crate::api::v1::cost_centers::restore_cost_center,
        crate::api::v1::cost_centers::list_deleted_cost_centers,
        crate::api::v1::cost_centers::destroy_cost_center,
        crate::api::v1::cost_centers::bulk_restore_cost_centers,
        // Customer Portal
        crate::api::v1::customer_portal::register_portal_user,
        crate::api::v1::customer_portal::login_portal_user,
        crate::api::v1::customer_portal::get_customer_orders,
        crate::api::v1::customer_portal::get_customer_invoices,
        crate::api::v1::customer_portal::get_customer_payments,
        crate::api::v1::customer_portal::get_invoice_pdf,
        crate::api::v1::customer_portal::create_support_ticket,
        crate::api::v1::customer_portal::get_support_tickets,
        // Vendor Portal
        crate::api::v1::vendor_portal::register_vendor_user,
        crate::api::v1::vendor_portal::login_vendor_user,
        crate::api::v1::vendor_portal::get_vendor_orders,
        crate::api::v1::vendor_portal::get_vendor_invoices,
        crate::api::v1::vendor_portal::get_vendor_payments,
        crate::api::v1::vendor_portal::get_vendor_invoice_pdf,
        crate::api::v1::vendor_portal::create_delivery_note,
        crate::api::v1::vendor_portal::get_delivery_notes,
        crate::api::v1::cost_centers::create_allocation,
        crate::api::v1::cost_centers::get_allocations,
        crate::api::v1::cost_centers::get_profitability,
        // Products
        crate::api::v1::product_variants::products::get_products,
        crate::api::v1::product_variants::products::create_product,
        crate::api::v1::product_variants::products::get_product,
        crate::api::v1::product_variants::products::update_product,
        crate::api::v1::product_variants::products::delete_product,
        crate::api::v1::product_variants::products::restore_product,
        crate::api::v1::product_variants::products::list_deleted_products,
        crate::api::v1::product_variants::products::destroy_product,
        crate::api::v1::product_variants::categories::get_categories,
        crate::api::v1::product_variants::categories::create_category,
        crate::api::v1::product_variants::categories::get_category,
        crate::api::v1::product_variants::categories::update_category,
        crate::api::v1::product_variants::categories::delete_category,
        crate::api::v1::product_variants::categories::restore_category,
        crate::api::v1::product_variants::categories::list_deleted_categories,
        crate::api::v1::product_variants::categories::destroy_category,
        crate::api::v1::product_variants::units::get_units,
        crate::api::v1::product_variants::units::create_unit,
        crate::api::v1::product_variants::units::get_unit,
        crate::api::v1::product_variants::units::update_unit,
        crate::api::v1::product_variants::units::delete_unit,
        crate::api::v1::product_variants::units::restore_unit,
        crate::api::v1::product_variants::units::list_deleted_units,
        crate::api::v1::product_variants::units::destroy_unit,
        crate::api::v1::product_variants::variants::create_variant,
        crate::api::v1::product_variants::variants::get_variants_by_product,
        crate::api::v1::product_variants::variants::get_variant,
        crate::api::v1::product_variants::variants::update_variant,
        crate::api::v1::product_variants::variants::delete_variant,
        crate::api::v1::product_variants::variants::restore_variant,
        crate::api::v1::product_variants::variants::list_deleted_variants,
        crate::api::v1::product_variants::variants::destroy_variant,
        // Feature Flags
        crate::api::v1::feature_flags::create_flag,
        crate::api::v1::feature_flags::get_flags,
        crate::api::v1::feature_flags::get_flag_by_id,
        crate::api::v1::feature_flags::update_flag,
        crate::api::v1::feature_flags::delete_flag,
        crate::api::v1::feature_flags::soft_delete_flag,
        crate::api::v1::feature_flags::restore_flag,
        crate::api::v1::feature_flags::list_deleted_flags,
        crate::api::v1::feature_flags::destroy_flag,
        crate::api::v1::feature_flags::enable_flag,
        crate::api::v1::feature_flags::disable_flag,
        crate::api::v1::feature_flags::check_feature,
        // Forecasting
        crate::api::v1::forecasting::forecast_demand,
        crate::api::v1::forecasting::get_reorder_suggestions,
        crate::api::v1::forecasting::get_stock_alerts,
        crate::api::v1::forecasting::get_forecast_report,
        // Audit
        crate::api::v1::audit::get_audit_logs,
        // Custom Fields
        crate::api::v1::custom_fields::create_custom_field,
        crate::api::v1::custom_fields::list_custom_fields,
        crate::api::v1::custom_fields::get_custom_field,
        crate::api::v1::custom_fields::update_custom_field,
        crate::api::v1::custom_fields::delete_custom_field,
        crate::api::v1::custom_fields::restore_custom_field,
        crate::api::v1::custom_fields::list_deleted_custom_fields,
        crate::api::v1::custom_fields::destroy_custom_field,
        // Settings
        crate::api::v1::settings::create_setting,
        crate::api::v1::settings::list_settings,
        crate::api::v1::settings::get_setting_by_key,
        crate::api::v1::settings::update_setting,
        crate::api::v1::settings::bulk_update_settings,
        crate::api::v1::settings::delete_setting,
        crate::api::v1::settings::soft_delete_setting,
        crate::api::v1::settings::restore_setting,
        crate::api::v1::settings::list_deleted_settings,
        crate::api::v1::settings::destroy_setting,
        crate::api::v1::settings::seed_settings,
        // API Keys
        crate::api::v1::api_keys::create_api_key,
        crate::api::v1::api_keys::list_api_keys,
        crate::api::v1::api_keys::list_api_keys_paginated,
        crate::api::v1::api_keys::get_api_key,
        crate::api::v1::api_keys::update_api_key,
        crate::api::v1::api_keys::delete_api_key,
        crate::api::v1::api_keys::soft_delete_api_key,
        crate::api::v1::api_keys::restore_api_key,
        crate::api::v1::api_keys::list_deleted_api_keys,
        crate::api::v1::api_keys::destroy_api_key,
        crate::api::v1::api_keys::check_scope,
        // IP Whitelist
        crate::api::v1::ip_whitelist::list_ip_whitelist,
        crate::api::v1::ip_whitelist::add_ip_whitelist_entry,
        crate::api::v1::ip_whitelist::remove_ip_whitelist_entry,
        crate::api::v1::ip_whitelist::update_ip_whitelist_entry,
        crate::api::v1::ip_whitelist::get_ip_whitelist_entry,
        // Archive
        crate::api::v1::archive::create_policy,
        crate::api::v1::archive::list_policies,
        crate::api::v1::archive::list_active_policies,
        crate::api::v1::archive::get_policy,
        crate::api::v1::archive::update_policy,
        crate::api::v1::archive::delete_policy,
        crate::api::v1::archive::create_job,
        crate::api::v1::archive::list_jobs,
        crate::api::v1::archive::get_job,
        crate::api::v1::archive::delete_job,
        crate::api::v1::archive::list_records,
        crate::api::v1::archive::get_record,
        crate::api::v1::archive::restore_records,
        crate::api::v1::archive::delete_record,
        // Jobs
        crate::api::v1::jobs::schedule_job,
        crate::api::v1::jobs::next_pending_job,
        crate::api::v1::jobs::get_job,
        crate::api::v1::jobs::start_job,
        crate::api::v1::jobs::complete_job,
        crate::api::v1::jobs::fail_job,
        crate::api::v1::jobs::cancel_job,
        crate::api::v1::jobs::retry_job,
        crate::api::v1::jobs::list_jobs_by_status,
        crate::api::v1::jobs::cleanup_jobs,
        // Notifications
        crate::api::v1::notifications::send_notification,
        crate::api::v1::notifications::get_in_app_notifications,
        crate::api::v1::notifications::get_unread_count,
        crate::api::v1::notifications::mark_notification_read,
        crate::api::v1::notifications::mark_all_read,
        crate::api::v1::notifications::retry_notification,
        crate::api::v1::notifications::soft_delete_notification,
        crate::api::v1::notifications::restore_notification,
        crate::api::v1::notifications::list_deleted_notifications,
        crate::api::v1::notifications::destroy_notification,
        // Push Notifications
        crate::api::v1::push_notifications::register_push_token,
        crate::api::v1::push_notifications::unregister_push_token,
        crate::api::v1::push_notifications::send_push,
        crate::api::v1::push_notifications::broadcast_push,
        crate::api::v1::push_notifications::get_user_push_tokens,
        // Observability
        crate::api::v1::observability::health,
        crate::api::v1::observability::health_live,
        crate::api::v1::observability::health_ready,
        crate::api::v1::observability::list_slis,
        crate::api::v1::observability::create_sli,
        crate::api::v1::observability::record_sli,
        crate::api::v1::observability::list_slos,
        crate::api::v1::observability::create_slo,
        crate::api::v1::observability::get_slo_compliance,
        crate::api::v1::observability::evaluate_slo_compliance,
        crate::api::v1::observability::list_alert_rules,
        crate::api::v1::observability::create_alert_rule,
        crate::api::v1::observability::delete_alert_rule,
        crate::api::v1::observability::evaluate_alerts,
        crate::api::v1::observability::list_alerts,
        crate::api::v1::observability::resolve_alert,
        crate::api::v1::observability::get_dashboard,
        crate::api::v1::observability::get_sparkline,
        crate::api::v1::observability::get_aspire_dashboard_url,
        // Reports
        crate::api::v1::reports::generate_report,
        crate::api::v1::reports::list_reports,
        crate::api::v1::reports::download_report,
        crate::api::v1::reports::delete_report,
        // Events
        crate::api::v1::events::publish_event,
        crate::api::v1::events::process_outbox,
        crate::api::v1::events::get_pending_events,
        crate::api::v1::events::retry_outbox_event,
        crate::api::v1::events::get_dead_letters,
        crate::api::v1::events::retry_dead_letter,
        crate::api::v1::events::get_dlq,
        crate::api::v1::events::retry_dlq,
        crate::api::v1::events::get_cdc_status,
        // Search
        crate::api::v1::search::search,
        crate::api::v1::search::index_document,
        crate::api::v1::search::remove_document,
        crate::api::v1::search::reindex,
        // Subscriptions
        crate::api::v1::subscriptions::create_plan,
        crate::api::v1::subscriptions::get_plan,
        crate::api::v1::subscriptions::list_plans,
        crate::api::v1::subscriptions::update_plan,
        crate::api::v1::subscriptions::delete_plan,
        crate::api::v1::subscriptions::create_subscription,
        crate::api::v1::subscriptions::get_subscription,
        crate::api::v1::subscriptions::list_subscriptions,
        crate::api::v1::subscriptions::update_subscription,
        crate::api::v1::subscriptions::delete_subscription,
        crate::api::v1::subscriptions::renew_subscription,
        crate::api::v1::subscriptions::due_for_billing,
        crate::api::v1::subscriptions::get_subscription_invoices,
        // Tax
        crate::api::v1::tax::rates::create_tax_rate,
        crate::api::v1::tax::rates::list_tax_rates,
        crate::api::v1::tax::rates::get_tax_rate,
        crate::api::v1::tax::rates::update_tax_rate,
        crate::api::v1::tax::rates::get_effective_rate,
        crate::api::v1::tax::rates::calculate_tax,
        crate::api::v1::tax::rates::calculate_invoice_tax,
        crate::api::v1::tax::periods::create_tax_period,
        crate::api::v1::tax::periods::list_tax_periods,
        crate::api::v1::tax::periods::get_tax_period,
        crate::api::v1::tax::periods::calculate_tax_period,
        crate::api::v1::tax::periods::file_tax_period,
        crate::api::v1::tax::rates::delete_tax_rate,
        crate::api::v1::tax::rates::restore_tax_rate,
        crate::api::v1::tax::rates::list_deleted_tax_rates,
        crate::api::v1::tax::rates::destroy_tax_rate,
        crate::api::v1::tax::rates::bulk_restore_tax_rates,
        crate::api::v1::tax::periods::delete_tax_period,
        crate::api::v1::tax::periods::restore_tax_period,
        crate::api::v1::tax::periods::list_deleted_tax_periods,
        crate::api::v1::tax::periods::destroy_tax_period,
        crate::api::v1::tax::periods::bulk_restore_tax_periods,
        // Currency
        crate::api::v1::currency::list_currencies,
        crate::api::v1::currency::create_currency,
        crate::api::v1::currency::get_currency,
        crate::api::v1::currency::update_currency,
        crate::api::v1::currency::soft_delete_currency,
        crate::api::v1::currency::restore_currency,
        crate::api::v1::currency::list_deleted_currencies,
        crate::api::v1::currency::destroy_currency,
        crate::api::v1::currency::list_exchange_rates,
        crate::api::v1::currency::create_exchange_rate,
        crate::api::v1::currency::convert_amount,
        crate::api::v1::currency::get_effective_rate,
        crate::api::v1::currency::soft_delete_exchange_rate,
        crate::api::v1::currency::restore_exchange_rate,
        crate::api::v1::currency::list_deleted_exchange_rates,
        crate::api::v1::currency::destroy_exchange_rate,
        // e-Fatura
        crate::api::v1::efatura::create_efatura,
        crate::api::v1::efatura::list_efaturas,
        crate::api::v1::efatura::get_efatura,
        crate::api::v1::efatura::get_efatura_xml,
        crate::api::v1::efatura::send_efatura,
        crate::api::v1::efatura::cancel_efatura,
        crate::api::v1::efatura::check_efatura_status,
        // e-Archive
        crate::api::v1::earchive::generate_earchive,
        crate::api::v1::earchive::list_earchives,
        crate::api::v1::earchive::get_earchive,
        crate::api::v1::earchive::sign_earchive,
        crate::api::v1::earchive::send_earchive,
        crate::api::v1::earchive::cancel_earchive,
        // e-Defter
        crate::api::v1::edefter::create_period,
        crate::api::v1::edefter::list_periods,
        crate::api::v1::edefter::get_period,
        crate::api::v1::edefter::populate_period,
        crate::api::v1::edefter::validate_period,
        crate::api::v1::edefter::generate_yevmiye,
        crate::api::v1::edefter::generate_buyuk_defter,
        crate::api::v1::edefter::sign_berat,
        crate::api::v1::edefter::send_to_saklayici,
        crate::api::v1::edefter::check_status,
        // e-Defter Blockchain
        crate::api::v1::edefter_blockchain::get_hash_chain,
        crate::api::v1::edefter_blockchain::build_merkle_tree,
        crate::api::v1::edefter_blockchain::verify_period,
        crate::api::v1::edefter_blockchain::get_hash_state,
        // Dashboard
        crate::api::v1::dashboard::get_all_kpis,
        crate::api::v1::dashboard::get_single_kpi,
        crate::api::v1::dashboard::get_sales_chart,
        crate::api::v1::dashboard::get_revenue_by_category_chart,
        crate::api::v1::dashboard::get_top_products_chart,
        crate::api::v1::dashboard::create_widget,
        crate::api::v1::dashboard::list_widgets,
        crate::api::v1::dashboard::delete_widget,
        // Resilience
        crate::api::v1::resilience::list_circuit_breakers,
        crate::api::v1::resilience::reset_circuit_breaker,
        crate::api::v1::resilience::get_retry_stats,
        // Workflows
        crate::api::v1::workflows::create_template,
        crate::api::v1::workflows::list_templates,
        crate::api::v1::workflows::start_workflow,
        crate::api::v1::workflows::approve_step,
        crate::api::v1::workflows::reject_step,
        crate::api::v1::workflows::resubmit_workflow,
        crate::api::v1::workflows::get_pending_approvals,
        crate::api::v1::workflows::get_instance,
        crate::api::v1::workflows::get_instance_audit,
        // Shift Planning
        crate::api::v1::shifts::create_shift,
        crate::api::v1::shifts::get_shifts,
        crate::api::v1::shifts::get_shift,
        crate::api::v1::shifts::update_shift,
        crate::api::v1::shifts::delete_shift,
        crate::api::v1::shifts::soft_delete_shift,
        crate::api::v1::shifts::restore_shift,
        crate::api::v1::shifts::list_deleted_shifts,
        crate::api::v1::shifts::destroy_shift,
        crate::api::v1::shifts::create_assignment,
        crate::api::v1::shifts::get_assignments_by_employee,
        crate::api::v1::shifts::get_assignments_by_shift,
        crate::api::v1::shifts::delete_assignment,
        crate::api::v1::shifts::clock_in,
        crate::api::v1::shifts::clock_out,
        crate::api::v1::shifts::get_attendance_by_employee,
        crate::api::v1::shifts::generate_report,
        crate::api::v1::shifts::calculate_overtime,
    ),
    components(
        schemas(
            // Core
            LoginRequest,
            LoginResponse,
            RefreshTokenRequest,
            RegisterRequest,
            CreateUser,
            UpdateUser,
            UserResponse,
            // MFA
            crate::domain::mfa::model::MfaSetupResponse,
            crate::domain::mfa::model::MfaStatusResponse,
            crate::domain::mfa::model::VerifyTotpRequest,
            crate::domain::mfa::model::DisableMfaRequest,
            crate::domain::mfa::model::VerifyMfaRequest,
            crate::domain::mfa::model::BackupCodesResponse,
            crate::domain::mfa::model::MfaMethod,
            MessageResponse,
            crate::error::ErrorResponse,
            // LDAP
            crate::domain::ldap::model::LdapConfigResponse,
            crate::domain::ldap::model::LdapSyncResult,
            crate::domain::ldap::model::LdapUser,
            crate::domain::ldap::model::CreateLdapConfig,
            crate::domain::ldap::model::UpdateLdapConfig,
            crate::domain::ldap::model::TestLdapConnectionRequest,
            crate::api::v1::ldap::LdapConnectionTestResponse,
            crate::common::PaginationParams,
            // Feature flags
            CreateFeatureFlag,
            UpdateFeatureFlag,
            FeatureFlagResponse,
            FeatureFlagStatus,
            crate::api::v1::feature_flags::FeatureStatusResponse,
            // Jobs
            crate::api::v1::jobs::JobResponse,
            crate::api::v1::jobs::CreateJobRequest,
            crate::api::v1::jobs::FailJobRequest,
            // API Keys
            crate::domain::api_key::model::CreateApiKey,
            crate::domain::api_key::model::UpdateApiKey,
            crate::domain::api_key::model::ApiKeyScope,
            // IP Whitelist
            crate::domain::ip_whitelist::model::CreateIpWhitelistEntry,
            crate::domain::ip_whitelist::model::UpdateIpWhitelistEntry,
            crate::domain::ip_whitelist::model::IpWhitelistEntryResponse,
            // Archive
            crate::domain::archive::model::ArchivePolicy,
            crate::domain::archive::model::ArchivePolicyResponse,
            crate::domain::archive::model::ArchiveJob,
            crate::domain::archive::model::ArchiveJobResponse,
            crate::domain::archive::model::ArchiveJobStatus,
            crate::domain::archive::model::ArchiveRecord,
            crate::domain::archive::model::ArchiveRecordResponse,
            crate::domain::archive::model::CreateArchivePolicy,
            crate::domain::archive::model::UpdateArchivePolicy,
            crate::domain::archive::model::CreateArchiveJob,
            crate::domain::archive::model::RestoreRequest,
            crate::domain::archive::model::BulkRestoreResponse<crate::domain::archive::model::ArchiveRecordResponse>,
            crate::domain::archive::model::BulkRestoreFailed,
            // Notifications
            crate::api::v1::notifications::SendNotificationRequest,
            crate::api::v1::notifications::InAppNotificationResponse,
            crate::api::v1::notifications::UnreadCountResponse,
            crate::api::v1::notifications::MarkReadResponse,
            // Push Notifications
            crate::api::v1::push_notifications::RegisterPushTokenRequest,
            crate::api::v1::push_notifications::UnregisterPushTokenRequest,
            crate::api::v1::push_notifications::SendPushRequest,
            crate::api::v1::push_notifications::BroadcastPushRequest,
            crate::api::v1::push_notifications::PushTokenResponse,
            crate::api::v1::push_notifications::BroadcastResponse,
            // Observability
            crate::domain::observability::model::SystemHealthSummary,
            crate::domain::observability::model::HealthCheckResult,
            crate::domain::observability::model::HealthStatus,
            crate::domain::observability::model::SliDefinition,
            crate::domain::observability::model::SliMetricType,
            crate::domain::observability::model::SloDefinition,
            crate::domain::observability::model::SloCompliance,
            crate::domain::observability::model::SloStatus,
            crate::domain::observability::model::Alert,
            crate::domain::observability::model::AlertRule,
            crate::domain::observability::model::AlertSeverity,
            crate::domain::observability::model::AlertState,
            crate::domain::observability::model::SparklineDataPoint,
            crate::api::v1::observability::CreateSliRequest,
            crate::api::v1::observability::CreateSloRequest,
            crate::api::v1::observability::CreateAlertRuleRequest,
            crate::api::v1::observability::EvaluateAlertsRequest,
            crate::api::v1::observability::AspireDashboardUrlResponse,
            crate::domain::observability::service::DashboardSummary,
            crate::domain::notification::model::NotificationResponse,
            crate::domain::notification::model::NotificationPreferenceResponse,
            // Reports
            crate::api::v1::reports::GenerateReportRequest,
            crate::api::v1::reports::ReportMetaResponse,
            // Events
            crate::api::v1::events::PublishEventRequest,
            crate::api::v1::events::OutboxEventResponse,
            crate::api::v1::events::DeadLetterResponse,
            crate::api::v1::events::ProcessOutboxResponse,
            crate::api::v1::events::CdcStatusResponse,
            // Chart of Accounts
            crate::domain::chart_of_accounts::model::AccountGroup,
            crate::domain::chart_of_accounts::model::ChartAccount,
            crate::domain::chart_of_accounts::model::ChartAccountResponse,
            crate::domain::chart_of_accounts::model::CreateChartAccount,
            crate::domain::chart_of_accounts::model::UpdateChartAccount,
            crate::domain::chart_of_accounts::model::AccountTreeNode,
            crate::domain::chart_of_accounts::model::TrialBalanceEntry,
            // Cost Centers
            crate::domain::cost_center::model::CostCenter,
            crate::domain::cost_center::model::CostCenterType,
            crate::domain::cost_center::model::CostCenterResponse,
            crate::domain::cost_center::model::CreateCostCenter,
            crate::domain::cost_center::model::UpdateCostCenter,
            crate::domain::cost_center::model::CostCenterAllocation,
            crate::domain::cost_center::model::AllocationResponse,
            crate::domain::cost_center::model::CreateAllocation,
            crate::domain::cost_center::model::ProfitabilityReport,
            crate::domain::cost_center::model::BulkRestoreResponse<crate::domain::cost_center::model::CostCenterResponse>,
            crate::domain::cost_center::model::BulkRestoreFailed,
            crate::api::v1::cost_centers::BulkRestoreRequest,
            crate::api::v1::cost_centers::ProfitabilityQuery,
            // Search
            crate::api::v1::search::SearchRequest,
            crate::api::v1::search::SearchResultResponse,
            crate::api::v1::search::IndexDocumentRequest,
            // Rate Limits
            crate::api::v1::rate_limits::RateLimitDashboardResponse,
            crate::api::v1::rate_limits::RateLimitEntryResponse,
            // Tax
            crate::domain::tax::model::TaxType,
            crate::domain::tax::model::TaxRate,
            crate::domain::tax::model::TaxCalculationResult,
            crate::domain::tax::model::TaxPeriodStatus,
            crate::domain::tax::model::TaxPeriod,
            crate::domain::tax::model::TaxPeriodDetail,
            crate::domain::tax::model::CreateTaxRate,
            crate::domain::tax::model::UpdateTaxRate,
            crate::domain::tax::model::CreateTaxPeriod,
            crate::domain::tax::model::TaxRateResponse,
            crate::domain::tax::model::TaxPeriodResponse,
            crate::domain::tax::model::BulkRestoreFailed,
            crate::api::v1::tax::CalculateTaxRequest,
            crate::api::v1::tax::CalculateInvoiceTaxRequest,
            crate::api::v1::tax::EffectiveRateQuery,
            // Currency
            crate::domain::currency::model::Currency,
            crate::domain::currency::model::CreateCurrency,
            crate::domain::currency::model::UpdateCurrency,
            crate::domain::currency::model::CurrencyResponse,
            crate::domain::currency::model::ExchangeRate,
            crate::domain::currency::model::CreateExchangeRate,
            crate::domain::currency::model::UpdateExchangeRate,
            crate::domain::currency::model::ExchangeRateResponse,
            crate::domain::currency::model::ConversionResult,
            // Goods Receipts
            crate::domain::purchase::model::GoodsReceipt,
            crate::domain::purchase::model::GoodsReceiptResponse,
            crate::domain::purchase::model::CreateGoodsReceipt,
            crate::domain::purchase::model::GoodsReceiptStatus,
            crate::api::v1::goods_receipts::UpdateReceiptStatusRequest,
            // e-Fatura
            crate::domain::efatura::model::EFaturaStatus,
            crate::domain::efatura::model::EFaturaProfile,
            crate::domain::efatura::model::EFaturaResponse,
            crate::domain::efatura::model::CreateEFatura,
            crate::api::v1::efatura::CancelEFaturaRequest,
            // e-Archive
            crate::domain::earchive::model::EarchiveStatus,
            crate::domain::earchive::model::EarchiveType,
            crate::domain::earchive::model::EarchiveResponse,
            crate::domain::earchive::model::CreateEarchiveDocument,
            crate::domain::earchive::model::GenerateEarchiveRequest,
            // e-Defter
            crate::domain::edefter::model::EDefterStatus,
            crate::domain::edefter::model::LedgerType,
            crate::domain::edefter::model::LedgerPeriod,
            crate::domain::edefter::model::LedgerPeriodResponse,
            crate::domain::edefter::model::CreateLedgerPeriod,
            crate::domain::edefter::model::YevmiyeEntry,
            crate::domain::edefter::model::YevmiyeLine,
            crate::domain::edefter::model::BalanceCheckResult,
            crate::domain::edefter::model::BeratInfo,
            crate::api::v1::edefter::XmlResponse,
            // Dashboard
            crate::domain::dashboard::model::KpiWidget,
            crate::domain::dashboard::model::KpiFormat,
            crate::domain::dashboard::model::ChartData,
            crate::domain::dashboard::model::ChartDataset,
            crate::domain::dashboard::model::DashboardFilter,
            crate::domain::dashboard::model::DashboardWidgetConfig,
            crate::domain::dashboard::model::CreateWidgetConfig,
            crate::domain::dashboard::model::WidgetType,
            crate::domain::dashboard::model::WidgetPosition,
            crate::domain::dashboard::model::KpiResponse,
            crate::domain::dashboard::model::AgingBucket,
            crate::domain::dashboard::model::TopProduct,
            crate::domain::dashboard::model::SalesPeriod,
            crate::domain::dashboard::model::RevenueByCategory,
            crate::domain::dashboard::model::ExpenseSummary,
            crate::domain::dashboard::model::KpiName,
            crate::api::v1::dashboard::ChartPeriodQuery,
            // Bank
            crate::domain::bank::model::BankCode,
            crate::domain::bank::model::BankAccount,
            crate::domain::bank::model::BankAccountResponse,
            crate::domain::bank::model::CreateBankAccount,
            crate::domain::bank::model::UpdateBankAccount,
            crate::domain::bank::model::BankStatement,
            crate::domain::bank::model::ImportBankStatement,
            crate::domain::bank::model::StatementFormat,
            crate::domain::bank::model::BankTransaction,
            crate::domain::bank::model::BankTransactionResponse,
            crate::domain::bank::model::MatchStatus,
            crate::domain::bank::model::MatchTransaction,
            crate::domain::bank::model::ReconciliationRule,
            crate::domain::bank::model::CreateReconciliationRule,
            crate::domain::bank::model::UpdateReconciliationRule,
            crate::domain::bank::model::MatchField,
            crate::domain::bank::model::ReconciliationReport,
            // Subscriptions
            crate::domain::subscription::model::BillingCycle,
            crate::domain::subscription::model::SubscriptionStatus,
            crate::domain::subscription::model::SubscriptionInvoiceStatus,
            crate::domain::subscription::model::SubscriptionPlan,
            crate::domain::subscription::model::SubscriptionPlanResponse,
            crate::domain::subscription::model::CreatePlan,
            crate::domain::subscription::model::UpdatePlan,
            crate::domain::subscription::model::Subscription,
            crate::domain::subscription::model::SubscriptionResponse,
            crate::domain::subscription::model::CreateSubscription,
            crate::domain::subscription::model::UpdateSubscription,
            crate::domain::subscription::model::SubscriptionInvoice,
            crate::domain::subscription::model::SubscriptionInvoiceResponse,
            crate::api::v1::subscriptions::DueForBillingQuery,
            // Webhooks
            crate::domain::webhook::model::WebhookStatus,
            crate::domain::webhook::model::DeliveryStatus,
            crate::domain::webhook::model::CreateWebhook,
            crate::domain::webhook::model::UpdateWebhook,
            crate::domain::webhook::model::WebhookResponse,
            crate::domain::webhook::model::WebhookDeliveryResponse,
            // Resilience
            crate::common::circuit_breaker::CircuitBreakerStats,
            crate::common::circuit_breaker::CircuitState,
            crate::common::circuit_breaker::CircuitBreakerConfig,
            crate::common::retry::RetryStatsSnapshot,
            crate::common::retry::RetryConfig,
            crate::api::v1::resilience::CircuitBreakerListResponse,
            crate::api::v1::resilience::CircuitBreakerResetResponse,
            crate::api::v1::resilience::RetryStatsResponse,
            crate::api::v1::resilience::ServicePath,
            // Barcodes
            crate::domain::barcode::model::BarcodeConfig,
            crate::domain::barcode::model::BarcodeType,
            crate::domain::barcode::model::BarcodeResponse,
            crate::domain::barcode::model::CreateBarcode,
            crate::domain::barcode::model::GenerateBarcodeRequest,
            crate::api::v1::barcode::ListBarcodesQuery,
            // Forecasting
            crate::domain::forecasting::model::DemandForecast,
            crate::domain::forecasting::model::DemandDataPoint,
            crate::domain::forecasting::model::ForecastPeriod,
            crate::domain::forecasting::model::ForecastReport,
            crate::domain::forecasting::model::ForecastRequest,
            crate::domain::forecasting::model::ReorderRequest,
            crate::domain::forecasting::model::ReorderSuggestion,
            crate::domain::forecasting::model::ReorderUrgency,
            crate::domain::forecasting::model::StockAlert,
            crate::domain::forecasting::model::StockAlertRequest,
            crate::domain::forecasting::model::StockAlertType,
            crate::api::v1::forecasting::ForecastReportQuery,
            // Workflows
            crate::domain::workflow::model::WorkflowTemplate,
            crate::domain::workflow::model::CreateWorkflowTemplate,
            crate::domain::workflow::model::WorkflowTemplateResponse,
            crate::domain::workflow::model::WorkflowInstance,
            crate::domain::workflow::model::WorkflowInstanceResponse,
            crate::domain::workflow::model::WorkflowInstanceDetailResponse,
            crate::domain::workflow::model::WorkflowStep,
            crate::domain::workflow::model::WorkflowStepResponse,
            crate::domain::workflow::model::WorkflowAuditLog,
            crate::domain::workflow::model::WorkflowAuditLogResponse,
            crate::domain::workflow::model::ApproveStep,
            crate::domain::workflow::model::RejectStep,
            crate::domain::workflow::model::WorkflowStatus,
            crate::domain::workflow::model::WorkflowStepStatus,
            crate::domain::workflow::model::WorkflowEntityType,
            crate::api::v1::workflows::StartWorkflowRequest,
            // Shift Planning
            crate::domain::shift::model::Shift,
            crate::domain::shift::model::ShiftResponse,
            crate::domain::shift::model::ShiftType,
            crate::domain::shift::model::CreateShift,
            crate::domain::shift::model::UpdateShift,
            crate::domain::shift::model::ShiftAssignment,
            crate::domain::shift::model::CreateShiftAssignment,
            crate::domain::shift::model::AttendanceRecord,
            crate::domain::shift::model::AttendanceRecordResponse,
            crate::domain::shift::model::AttendanceStatus,
            crate::domain::shift::model::ClockInRequest,
            crate::domain::shift::model::ClockOutRequest,
            crate::domain::shift::model::ShiftReport,
            crate::domain::shift::model::ShiftReportQuery,
            crate::domain::shift::model::OvertimeCalculation,
            crate::api::v1::shifts::CalculateOvertimeRequest,
            // Customer Portal
            crate::domain::customer_portal::model::PortalUser,
            crate::domain::customer_portal::model::PortalAuthResponse,
            crate::domain::customer_portal::model::SupportTicket,
            crate::domain::customer_portal::model::CustomerOrderView,
            crate::domain::customer_portal::model::CustomerInvoiceView,
            crate::domain::customer_portal::model::CustomerPaymentView,
            crate::domain::customer_portal::model::PortalPaginationParams,
            crate::domain::customer_portal::model::CreatePortalUser,
            crate::domain::customer_portal::model::PortalLoginRequest,
            crate::domain::customer_portal::model::CreateSupportTicket,
            crate::domain::customer_portal::model::PortalUserProfile,
            crate::domain::customer_portal::model::PortalUserStatus,
            crate::domain::customer_portal::model::SupportTicketStatus,
            crate::domain::customer_portal::model::TicketPriority,
            crate::domain::customer_portal::model::TicketCategory,
            // Vendor Portal
            crate::domain::vendor_portal::model::VendorUser,
            crate::domain::vendor_portal::model::VendorAuthResponse,
            crate::domain::vendor_portal::model::DeliveryNote,
            crate::domain::vendor_portal::model::VendorOrderView,
            crate::domain::vendor_portal::model::VendorInvoiceView,
            crate::domain::vendor_portal::model::VendorPaymentView,
            crate::domain::vendor_portal::model::VendorPaginationParams,
            crate::domain::vendor_portal::model::CreateVendorUser,
            crate::domain::vendor_portal::model::VendorLoginRequest,
            crate::domain::vendor_portal::model::CreateDeliveryNote,
            crate::domain::vendor_portal::model::VendorUserProfile,
            crate::domain::vendor_portal::model::VendorUserStatus,
            crate::domain::vendor_portal::model::DeliveryNoteStatus,
        )
    ),
    security(
        ("bearer_auth" = [])
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Admin", description = "Administrative endpoints (rate limits, system status)"),
        (name = "Auth", description = "Authentication endpoints (login, register, token refresh)"),
        (name = "Bank", description = "Turkish bank integration, statements, transactions and reconciliation"),
        (name = "Barcodes", description = "Barcode and QR code generation for products and invoices"),
        (name = "Users", description = "User management endpoints (CRUD operations)"),
        (name = "Tenant", description = "Tenant management and configuration"),
        (name = "Cari", description = "Customer / Vendor accounts"),
        (name = "Stock", description = "Warehouses, stock movements and inventory"),
        (name = "Subscriptions", description = "Subscription plans, subscriptions, and SaaS billing"),
        (name = "Invoice", description = "Invoices and payments"),
        (name = "Sales", description = "Sales orders and quotations"),
        (name = "Purchase Orders", description = "Purchase orders and vendor management"),
        (name = "Purchase Requests", description = "Purchase requests and approval workflow"),
        (name = "Goods Receipts", description = "Goods receipts for purchase orders"),
        (name = "HR", description = "Employees, attendance, leave and payroll"),
        (name = "Accounting", description = "Chart of accounts and journal entries"),
        (name = "Assets", description = "Fixed assets, depreciation and maintenance"),
        (name = "Project", description = "Projects, WBS and costs"),
        (name = "Manufacturing", description = "Work orders, BOM, routing and quality control"),
        (name = "CRM", description = "Leads, opportunities, campaigns and tickets"),
        (name = "Products", description = "Product catalog, categories and variants"),
        (name = "Chart of Accounts", description = "Chart of accounts, account tree and trial balance"),
        (name = "Cost Centers", description = "Cost center and profit center management with allocations and profitability reports"),
        (name = "Customer Portal", description = "Self-service portal for customers to view orders, invoices, payments and support tickets"),
        (name = "Vendor Portal", description = "Self-service portal for vendors to view purchase orders, invoices, payments and delivery notes"),
        (name = "Feature Flags", description = "Feature flag management endpoints"),
        (name = "Forecasting", description = "Inventory demand forecasting, reorder suggestions and stock alerts"),
        (name = "Custom Fields", description = "Custom field definitions for dynamic module attributes"),
        (name = "Settings", description = "Configuration management endpoints"),
        (name = "Jobs", description = "Background job scheduler endpoints"),
        (name = "LDAP", description = "LDAP / Active Directory user synchronization and configuration"),
        (name = "API Keys", description = "API key management and scope validation"),
        (name = "IP Whitelist", description = "Tenant-scoped IP access control with CIDR support"),
        (name = "Archive", description = "Data archiving policies, jobs, and record restoration"),
        (name = "Notifications", description = "In-app notifications, email/SMS sending"),
        (name = "Push Notifications", description = "FCM push notification token management and delivery"),
        (name = "Reports", description = "Report generation and management"),
        (name = "Events", description = "Event bus, outbox pattern, and dead letter queue"),
        (name = "Search", description = "Full-text search across entities"),
        (name = "Tax", description = "Turkish tax rate management, calculation, and KVB period tracking"),
        (name = "Currency", description = "Multi-currency support, exchange rates and conversion"),
        (name = "Dashboard", description = "BI dashboard KPIs, charts and widget management"),
        (name = "e-Fatura", description = "Turkish e-Fatura (electronic invoicing) integration with GIB"),
        (name = "e-Archive", description = "Turkish e-Arşiv Fatura and E-Serbest Meslek Makbuzu integration with GIB"),
        (name = "e-Defter", description = "Turkish e-Defter (electronic ledger) integration with GIB"),
        (name = "Audit", description = "Audit log retrieval"),
        (name = "Webhooks", description = "Webhook endpoints and delivery management"),
        (name = "Resilience", description = "Circuit breaker and retry monitoring"),
        (name = "Workflows", description = "Configurable approval workflows for documents and business processes")
    )
)]
pub struct ApiDoc;

/// Security scheme addon for OpenAPI
pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
