//! API layer

pub mod v1;

// Legacy modules (deprecated, will be removed in v2)
pub mod auth;
pub mod users;

// Explicit re-exports to avoid ambiguity
pub use auth::configure as auth_configure;
pub use users::configure as users_configure;

// V1 re-exports
pub use v1::accounting_configure as v1_accounting_configure;
pub use v1::api_keys_configure as v1_api_keys_configure;
pub use v1::assets_configure as v1_assets_configure;
pub use v1::audit_configure as v1_audit_configure;
pub use v1::auth_configure as v1_auth_configure;
pub use v1::cari_configure as v1_cari_configure;
pub use v1::chart_of_accounts_configure as v1_chart_of_accounts_configure;
pub use v1::crm_configure as v1_crm_configure;
pub use v1::currency_configure as v1_currency_configure;
pub use v1::custom_fields_configure as v1_custom_fields_configure;
pub use v1::edefter_configure as v1_edefter_configure;
pub use v1::efatura_configure as v1_efatura_configure;
pub use v1::events_configure as v1_events_configure;
pub use v1::feature_flags_configure as v1_feature_flags_configure;
pub use v1::goods_receipts_configure as v1_goods_receipts_configure;
pub use v1::hr_configure as v1_hr_configure;
pub use v1::invoice_configure as v1_invoice_configure;
pub use v1::jobs_configure as v1_jobs_configure;
pub use v1::manufacturing_configure as v1_manufacturing_configure;
pub use v1::mfa_configure as v1_mfa_configure;
pub use v1::notifications_configure as v1_notifications_configure;
pub use v1::product_variants_configure as v1_product_variants_configure;
pub use v1::project_configure as v1_project_configure;
pub use v1::purchase_orders_configure as v1_purchase_orders_configure;
pub use v1::purchase_requests_configure as v1_purchase_requests_configure;
pub use v1::rate_limits_configure as v1_rate_limits_configure;
pub use v1::reports_configure as v1_reports_configure;
pub use v1::sales_configure as v1_sales_configure;
pub use v1::search_configure as v1_search_configure;
pub use v1::settings_configure as v1_settings_configure;
pub use v1::stock_configure as v1_stock_configure;
pub use v1::tax_configure as v1_tax_configure;
pub use v1::tenant_configure as v1_tenant_configure;
pub use v1::users_configure as v1_users_configure;
pub use v1::webhooks_configure as v1_webhooks_configure;

use crate::common::MessageResponse;
use crate::domain::auth::{LoginRequest, LoginResponse, RefreshTokenRequest, RegisterRequest};
use crate::domain::feature::{
    CreateFeatureFlag, FeatureFlagResponse, FeatureFlagStatus, UpdateFeatureFlag,
};
use crate::domain::user::{CreateUser, UpdateUser, UserResponse};
use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::Modify;
use utoipa::OpenApi;

/// OpenAPI specification for the Turerp ERP API
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Turerp ERP API",
        description = "Multi-tenant SaaS ERP system API\n\n## Authentication\n\nAll endpoints except `/api/v1/auth/login`, `/api/v1/auth/register`, and `/api/v1/auth/refresh` require JWT Bearer token authentication.\n\n## Rate Limiting\n\nAuthentication endpoints are rate limited to 10 requests per minute per IP address with a burst of 3 requests.\n\n## Localization\n\nAll endpoints support per-request localization via the `Accept-Language` header. Supported languages: `en` (default), `tr`.\n\n## API Versioning\n\n- `/api/v1/` - Current stable API (recommended)\n- `/api/auth/`, `/api/users/` - Legacy routes (deprecated, will be removed in v2)",
        version = "1.0.0",
        contact(
            name = "Turerp Team",
            email = "info@turerp.com"
        )
    ),
    paths(
        // Auth
        crate::api::v1::auth::register,
        crate::api::v1::auth::login,
        crate::api::v1::auth::refresh_token,
        crate::api::v1::auth::me,
        // MFA
        crate::api::v1::mfa::mfa_setup,
        crate::api::v1::mfa::mfa_verify_setup,
        crate::api::v1::mfa::mfa_disable,
        crate::api::v1::mfa::mfa_status,
        crate::api::v1::mfa::mfa_verify,
        crate::api::v1::mfa::mfa_regenerate_backup_codes,
        // Users
        crate::api::v1::users::create_user,
        crate::api::v1::users::get_user,
        crate::api::v1::users::get_users,
        crate::api::v1::users::update_user,
        crate::api::v1::users::delete_user,
        crate::api::v1::users::restore_user,
        crate::api::v1::users::list_deleted_users,
        crate::api::v1::users::destroy_user,
        // Webhooks
        crate::api::v1::webhooks::create_webhook,
        crate::api::v1::webhooks::list_webhooks,
        crate::api::v1::webhooks::get_webhook,
        crate::api::v1::webhooks::update_webhook,
        crate::api::v1::webhooks::delete_webhook,
        crate::api::v1::webhooks::restore_webhook,
        crate::api::v1::webhooks::list_deleted_webhooks,
        crate::api::v1::webhooks::destroy_webhook,
        crate::api::v1::webhooks::test_webhook,
        crate::api::v1::webhooks::list_deliveries,
        crate::api::v1::webhooks::retry_delivery,
        // Tenant
        crate::api::v1::tenant::create_tenant,
        crate::api::v1::tenant::get_tenants,
        crate::api::v1::tenant::get_tenant,
        crate::api::v1::tenant::update_tenant,
        crate::api::v1::tenant::delete_tenant,
        crate::api::v1::tenant::restore_tenant,
        crate::api::v1::tenant::list_deleted_tenants,
        crate::api::v1::tenant::destroy_tenant,
        crate::api::v1::tenant::create_tenant_config,
        crate::api::v1::tenant::get_tenant_configs,
        crate::api::v1::tenant::get_tenant_config,
        crate::api::v1::tenant::update_tenant_config,
        crate::api::v1::tenant::delete_tenant_config,
        // Cari
        crate::api::v1::cari::create_cari,
        crate::api::v1::cari::get_cari,
        crate::api::v1::cari::get_all_cari,
        crate::api::v1::cari::get_cari_by_type,
        crate::api::v1::cari::search_cari,
        crate::api::v1::cari::update_cari,
        crate::api::v1::cari::delete_cari,
        crate::api::v1::cari::restore_cari,
        crate::api::v1::cari::list_deleted_cari,
        crate::api::v1::cari::destroy_cari,
        // Stock
        crate::api::v1::stock::create_warehouse,
        crate::api::v1::stock::get_warehouses,
        crate::api::v1::stock::get_warehouse,
        crate::api::v1::stock::update_warehouse,
        crate::api::v1::stock::delete_warehouse,
        crate::api::v1::stock::restore_warehouse,
        crate::api::v1::stock::list_deleted_warehouses,
        crate::api::v1::stock::destroy_warehouse,
        crate::api::v1::stock::create_stock_movement,
        crate::api::v1::stock::get_stock_movements_by_product,
        crate::api::v1::stock::get_stock_movements_by_warehouse,
        crate::api::v1::stock::restore_stock_movement,
        crate::api::v1::stock::list_deleted_stock_movements,
        crate::api::v1::stock::destroy_stock_movement,
        crate::api::v1::stock::get_stock_by_product,
        crate::api::v1::stock::get_stock_by_warehouse,
        crate::api::v1::stock::restore_stock_level,
        crate::api::v1::stock::list_deleted_stock_levels,
        crate::api::v1::stock::destroy_stock_level,
        crate::api::v1::stock::get_stock_summary,
        // Invoice
        crate::api::v1::invoice::create_invoice,
        crate::api::v1::invoice::get_invoice,
        crate::api::v1::invoice::get_invoices,
        crate::api::v1::invoice::get_invoices_by_status,
        crate::api::v1::invoice::get_outstanding_invoices,
        crate::api::v1::invoice::get_overdue_invoices,
        crate::api::v1::invoice::update_invoice_status,
        crate::api::v1::invoice::delete_invoice,
        crate::api::v1::invoice::restore_invoice,
        crate::api::v1::invoice::list_deleted_invoices,
        crate::api::v1::invoice::destroy_invoice,
        crate::api::v1::invoice::create_payment,
        crate::api::v1::invoice::get_payments_by_invoice,
        // Sales
        crate::api::v1::sales::create_sales_order,
        crate::api::v1::sales::get_sales_orders,
        crate::api::v1::sales::get_sales_order,
        crate::api::v1::sales::get_sales_orders_by_status,
        crate::api::v1::sales::update_sales_order_status,
        crate::api::v1::sales::delete_sales_order,
        crate::api::v1::sales::restore_sales_order,
        crate::api::v1::sales::list_deleted_sales_orders,
        crate::api::v1::sales::destroy_sales_order,
        crate::api::v1::sales::create_quotation,
        crate::api::v1::sales::get_quotations,
        crate::api::v1::sales::get_quotation,
        crate::api::v1::sales::get_quotations_by_status,
        crate::api::v1::sales::update_quotation_status,
        crate::api::v1::sales::convert_quotation_to_order,
        crate::api::v1::sales::delete_quotation,
        crate::api::v1::sales::restore_quotation,
        crate::api::v1::sales::list_deleted_quotations,
        crate::api::v1::sales::destroy_quotation,
        // Purchase Orders
        crate::api::v1::purchase_orders::create_order,
        crate::api::v1::purchase_orders::get_orders,
        crate::api::v1::purchase_orders::get_order,
        crate::api::v1::purchase_orders::update_order_status,
        crate::api::v1::purchase_orders::delete_order,
        crate::api::v1::purchase_orders::restore_order,
        crate::api::v1::purchase_orders::list_deleted_orders,
        crate::api::v1::purchase_orders::destroy_order,
        // Purchase Requests
        crate::api::v1::purchase_requests::create_request,
        crate::api::v1::purchase_requests::get_requests,
        crate::api::v1::purchase_requests::get_request,
        crate::api::v1::purchase_requests::update_request,
        crate::api::v1::purchase_requests::submit_request,
        crate::api::v1::purchase_requests::approve_request,
        crate::api::v1::purchase_requests::reject_request,
        crate::api::v1::purchase_requests::delete_request,
        crate::api::v1::purchase_requests::restore_request,
        crate::api::v1::purchase_requests::list_deleted_requests,
        crate::api::v1::purchase_requests::destroy_request,
        // Rate Limits
        crate::api::v1::rate_limits::get_rate_limit_stats,
        // Goods Receipts
        crate::api::v1::goods_receipts::create_receipt,
        crate::api::v1::goods_receipts::get_receipt,
        crate::api::v1::goods_receipts::get_receipts_by_order,
        crate::api::v1::goods_receipts::update_receipt_status,
        crate::api::v1::goods_receipts::delete_receipt,
        crate::api::v1::goods_receipts::restore_receipt,
        crate::api::v1::goods_receipts::list_deleted_receipts,
        crate::api::v1::goods_receipts::destroy_receipt,
        // HR
        crate::api::v1::hr::create_employee,
        crate::api::v1::hr::get_employees,
        crate::api::v1::hr::get_employee,
        crate::api::v1::hr::update_employee_status,
        crate::api::v1::hr::terminate_employee,
        crate::api::v1::hr::soft_delete_employee,
        crate::api::v1::hr::restore_employee,
        crate::api::v1::hr::list_deleted_employees,
        crate::api::v1::hr::destroy_employee,
        crate::api::v1::hr::record_attendance,
        crate::api::v1::hr::get_attendance_by_employee,
        crate::api::v1::hr::soft_delete_attendance,
        crate::api::v1::hr::restore_attendance,
        crate::api::v1::hr::list_deleted_attendance,
        crate::api::v1::hr::destroy_attendance,
        crate::api::v1::hr::create_leave_request,
        crate::api::v1::hr::get_leave_requests_by_employee,
        crate::api::v1::hr::approve_leave_request,
        crate::api::v1::hr::reject_leave_request,
        crate::api::v1::hr::soft_delete_leave_request,
        crate::api::v1::hr::restore_leave_request,
        crate::api::v1::hr::list_deleted_leave_requests,
        crate::api::v1::hr::destroy_leave_request,
        crate::api::v1::hr::get_leave_types,
        crate::api::v1::hr::soft_delete_leave_type,
        crate::api::v1::hr::restore_leave_type,
        crate::api::v1::hr::list_deleted_leave_types,
        crate::api::v1::hr::destroy_leave_type,
        crate::api::v1::hr::calculate_payroll,
        crate::api::v1::hr::get_payroll_by_employee,
        crate::api::v1::hr::mark_payroll_paid,
        crate::api::v1::hr::soft_delete_payroll,
        crate::api::v1::hr::restore_payroll,
        crate::api::v1::hr::list_deleted_payroll,
        crate::api::v1::hr::destroy_payroll,
        // Accounting
        crate::api::v1::accounting::create_account,
        crate::api::v1::accounting::get_accounts,
        crate::api::v1::accounting::get_accounts_by_type,
        crate::api::v1::accounting::get_account,
        crate::api::v1::accounting::soft_delete_account,
        crate::api::v1::accounting::restore_account,
        crate::api::v1::accounting::list_deleted_accounts,
        crate::api::v1::accounting::destroy_account,
        crate::api::v1::accounting::create_journal_entry,
        crate::api::v1::accounting::get_journal_entries,
        crate::api::v1::accounting::get_journal_entry,
        crate::api::v1::accounting::post_journal_entry,
        crate::api::v1::accounting::void_journal_entry,
        crate::api::v1::accounting::soft_delete_journal_entry,
        crate::api::v1::accounting::restore_journal_entry,
        crate::api::v1::accounting::list_deleted_journal_entries,
        crate::api::v1::accounting::destroy_journal_entry,
        crate::api::v1::accounting::generate_trial_balance,
        // Assets
        crate::api::v1::assets::create_asset,
        crate::api::v1::assets::get_assets,
        crate::api::v1::assets::get_asset,
        crate::api::v1::assets::get_assets_by_status,
        crate::api::v1::assets::update_asset,
        crate::api::v1::assets::update_asset_status,
        crate::api::v1::assets::calculate_depreciation,
        crate::api::v1::assets::record_depreciation,
        crate::api::v1::assets::dispose_asset,
        crate::api::v1::assets::write_off_asset,
        crate::api::v1::assets::start_maintenance,
        crate::api::v1::assets::end_maintenance,
        crate::api::v1::assets::soft_delete_asset,
        crate::api::v1::assets::restore_asset,
        crate::api::v1::assets::list_deleted_assets,
        crate::api::v1::assets::destroy_asset,
        crate::api::v1::assets::create_maintenance_record,
        crate::api::v1::assets::get_maintenance_records,
        // Project
        crate::api::v1::project::create_project,
        crate::api::v1::project::get_projects,
        crate::api::v1::project::get_project,
        crate::api::v1::project::update_project_status,
        crate::api::v1::project::soft_delete_project,
        crate::api::v1::project::restore_project,
        crate::api::v1::project::list_deleted_projects,
        crate::api::v1::project::destroy_project,
        crate::api::v1::project::create_wbs_item,
        crate::api::v1::project::get_wbs_by_project,
        crate::api::v1::project::update_wbs_progress,
        crate::api::v1::project::create_project_cost,
        crate::api::v1::project::get_project_costs,
        crate::api::v1::project::get_profitability,
        // Manufacturing
        crate::api::v1::manufacturing::create_work_order,
        crate::api::v1::manufacturing::get_work_orders,
        crate::api::v1::manufacturing::get_work_order,
        crate::api::v1::manufacturing::update_work_order_status,
        crate::api::v1::manufacturing::soft_delete_work_order,
        crate::api::v1::manufacturing::restore_work_order,
        crate::api::v1::manufacturing::list_deleted_work_orders,
        crate::api::v1::manufacturing::destroy_work_order,
        crate::api::v1::manufacturing::add_work_order_operation,
        crate::api::v1::manufacturing::get_work_order_operations,
        crate::api::v1::manufacturing::add_work_order_material,
        crate::api::v1::manufacturing::get_work_order_materials,
        crate::api::v1::manufacturing::create_bom,
        crate::api::v1::manufacturing::get_bom,
        crate::api::v1::manufacturing::get_boms_by_product,
        crate::api::v1::manufacturing::add_bom_line,
        crate::api::v1::manufacturing::get_bom_lines,
        crate::api::v1::manufacturing::soft_delete_bom,
        crate::api::v1::manufacturing::restore_bom,
        crate::api::v1::manufacturing::list_deleted_boms,
        crate::api::v1::manufacturing::destroy_bom,
        crate::api::v1::manufacturing::create_routing,
        crate::api::v1::manufacturing::get_routing,
        crate::api::v1::manufacturing::get_routings_by_product,
        crate::api::v1::manufacturing::add_routing_operation,
        crate::api::v1::manufacturing::soft_delete_routing,
        crate::api::v1::manufacturing::restore_routing,
        crate::api::v1::manufacturing::list_deleted_routings,
        crate::api::v1::manufacturing::destroy_routing,
        crate::api::v1::manufacturing::calculate_material_requirements,
        crate::api::v1::manufacturing::create_inspection,
        crate::api::v1::manufacturing::get_inspections,
        crate::api::v1::manufacturing::get_inspection,
        crate::api::v1::manufacturing::update_inspection,
        crate::api::v1::manufacturing::delete_inspection,
        crate::api::v1::manufacturing::restore_inspection,
        crate::api::v1::manufacturing::list_deleted_inspections,
        crate::api::v1::manufacturing::destroy_inspection,
        crate::api::v1::manufacturing::create_ncr,
        crate::api::v1::manufacturing::get_ncrs,
        crate::api::v1::manufacturing::get_ncr,
        crate::api::v1::manufacturing::update_ncr,
        crate::api::v1::manufacturing::delete_ncr,
        crate::api::v1::manufacturing::restore_ncr,
        crate::api::v1::manufacturing::list_deleted_ncrs,
        crate::api::v1::manufacturing::destroy_ncr,
        // CRM
        crate::api::v1::crm::create_lead,
        crate::api::v1::crm::get_leads,
        crate::api::v1::crm::get_lead,
        crate::api::v1::crm::get_leads_by_status,
        crate::api::v1::crm::update_lead_status,
        crate::api::v1::crm::soft_delete_lead,
        crate::api::v1::crm::restore_lead,
        crate::api::v1::crm::list_deleted_leads,
        crate::api::v1::crm::destroy_lead,
        crate::api::v1::crm::convert_lead,
        crate::api::v1::crm::create_opportunity,
        crate::api::v1::crm::get_opportunities,
        crate::api::v1::crm::get_opportunity,
        crate::api::v1::crm::get_opportunities_by_status,
        crate::api::v1::crm::update_opportunity_status,
        crate::api::v1::crm::soft_delete_opportunity,
        crate::api::v1::crm::restore_opportunity,
        crate::api::v1::crm::list_deleted_opportunities,
        crate::api::v1::crm::destroy_opportunity,
        crate::api::v1::crm::get_pipeline_value,
        crate::api::v1::crm::create_campaign,
        crate::api::v1::crm::get_campaigns,
        crate::api::v1::crm::get_campaign,
        crate::api::v1::crm::get_campaigns_by_status,
        crate::api::v1::crm::update_campaign_status,
        crate::api::v1::crm::soft_delete_campaign,
        crate::api::v1::crm::restore_campaign,
        crate::api::v1::crm::list_deleted_campaigns,
        crate::api::v1::crm::destroy_campaign,
        crate::api::v1::crm::create_ticket,
        crate::api::v1::crm::get_tickets,
        crate::api::v1::crm::get_ticket,
        crate::api::v1::crm::get_tickets_by_status,
        crate::api::v1::crm::update_ticket_status,
        crate::api::v1::crm::soft_delete_ticket,
        crate::api::v1::crm::restore_ticket,
        crate::api::v1::crm::list_deleted_tickets,
        crate::api::v1::crm::destroy_ticket,
        crate::api::v1::crm::resolve_ticket,
        crate::api::v1::crm::get_open_tickets_count,
        // Chart of Accounts
        crate::api::v1::chart_of_accounts::create_chart_account,
        crate::api::v1::chart_of_accounts::list_chart_accounts,
        crate::api::v1::chart_of_accounts::get_chart_account_by_code,
        crate::api::v1::chart_of_accounts::update_chart_account,
        crate::api::v1::chart_of_accounts::soft_delete_chart_account,
        crate::api::v1::chart_of_accounts::restore_chart_account,
        crate::api::v1::chart_of_accounts::list_deleted_chart_accounts,
        crate::api::v1::chart_of_accounts::destroy_chart_account,
        crate::api::v1::chart_of_accounts::get_account_tree,
        crate::api::v1::chart_of_accounts::get_chart_account_children,
        crate::api::v1::chart_of_accounts::recalculate_chart_account_balance,
        crate::api::v1::chart_of_accounts::get_trial_balance,
        // Products
        crate::api::v1::product_variants::get_products,
        crate::api::v1::product_variants::create_product,
        crate::api::v1::product_variants::get_product,
        crate::api::v1::product_variants::update_product,
        crate::api::v1::product_variants::delete_product,
        crate::api::v1::product_variants::restore_product,
        crate::api::v1::product_variants::list_deleted_products,
        crate::api::v1::product_variants::destroy_product,
        crate::api::v1::product_variants::get_categories,
        crate::api::v1::product_variants::create_category,
        crate::api::v1::product_variants::get_category,
        crate::api::v1::product_variants::update_category,
        crate::api::v1::product_variants::delete_category,
        crate::api::v1::product_variants::restore_category,
        crate::api::v1::product_variants::list_deleted_categories,
        crate::api::v1::product_variants::destroy_category,
        crate::api::v1::product_variants::get_units,
        crate::api::v1::product_variants::create_unit,
        crate::api::v1::product_variants::get_unit,
        crate::api::v1::product_variants::update_unit,
        crate::api::v1::product_variants::delete_unit,
        crate::api::v1::product_variants::restore_unit,
        crate::api::v1::product_variants::list_deleted_units,
        crate::api::v1::product_variants::destroy_unit,
        crate::api::v1::product_variants::create_variant,
        crate::api::v1::product_variants::get_variants_by_product,
        crate::api::v1::product_variants::get_variant,
        crate::api::v1::product_variants::update_variant,
        crate::api::v1::product_variants::delete_variant,
        crate::api::v1::product_variants::restore_variant,
        crate::api::v1::product_variants::list_deleted_variants,
        crate::api::v1::product_variants::destroy_variant,
        // Feature Flags
        crate::api::v1::feature_flags::create_flag,
        crate::api::v1::feature_flags::get_flags,
        crate::api::v1::feature_flags::get_flag_by_id,
        crate::api::v1::feature_flags::update_flag,
        crate::api::v1::feature_flags::delete_flag,
        crate::api::v1::feature_flags::soft_delete_flag,
        crate::api::v1::feature_flags::restore_flag,
        crate::api::v1::feature_flags::list_deleted_flags,
        crate::api::v1::feature_flags::destroy_flag,
        crate::api::v1::feature_flags::enable_flag,
        crate::api::v1::feature_flags::disable_flag,
        crate::api::v1::feature_flags::check_feature,
        // Audit
        crate::api::v1::audit::get_audit_logs,
        // Custom Fields
        crate::api::v1::custom_fields::create_custom_field,
        crate::api::v1::custom_fields::list_custom_fields,
        crate::api::v1::custom_fields::get_custom_field,
        crate::api::v1::custom_fields::update_custom_field,
        crate::api::v1::custom_fields::delete_custom_field,
        crate::api::v1::custom_fields::restore_custom_field,
        crate::api::v1::custom_fields::list_deleted_custom_fields,
        crate::api::v1::custom_fields::destroy_custom_field,
        // Settings
        crate::api::v1::settings::create_setting,
        crate::api::v1::settings::list_settings,
        crate::api::v1::settings::get_setting_by_key,
        crate::api::v1::settings::update_setting,
        crate::api::v1::settings::bulk_update_settings,
        crate::api::v1::settings::delete_setting,
        crate::api::v1::settings::soft_delete_setting,
        crate::api::v1::settings::restore_setting,
        crate::api::v1::settings::list_deleted_settings,
        crate::api::v1::settings::destroy_setting,
        crate::api::v1::settings::seed_settings,
        // API Keys
        crate::api::v1::api_keys::create_api_key,
        crate::api::v1::api_keys::list_api_keys,
        crate::api::v1::api_keys::list_api_keys_paginated,
        crate::api::v1::api_keys::get_api_key,
        crate::api::v1::api_keys::update_api_key,
        crate::api::v1::api_keys::delete_api_key,
        crate::api::v1::api_keys::soft_delete_api_key,
        crate::api::v1::api_keys::restore_api_key,
        crate::api::v1::api_keys::list_deleted_api_keys,
        crate::api::v1::api_keys::destroy_api_key,
        crate::api::v1::api_keys::check_scope,
        // Jobs
        crate::api::v1::jobs::schedule_job,
        crate::api::v1::jobs::next_pending_job,
        crate::api::v1::jobs::get_job,
        crate::api::v1::jobs::start_job,
        crate::api::v1::jobs::complete_job,
        crate::api::v1::jobs::fail_job,
        crate::api::v1::jobs::cancel_job,
        crate::api::v1::jobs::retry_job,
        crate::api::v1::jobs::list_jobs_by_status,
        crate::api::v1::jobs::cleanup_jobs,
        // Notifications
        crate::api::v1::notifications::send_notification,
        crate::api::v1::notifications::get_in_app_notifications,
        crate::api::v1::notifications::get_unread_count,
        crate::api::v1::notifications::mark_notification_read,
        crate::api::v1::notifications::mark_all_read,
        crate::api::v1::notifications::retry_notification,
        crate::api::v1::notifications::soft_delete_notification,
        crate::api::v1::notifications::restore_notification,
        crate::api::v1::notifications::list_deleted_notifications,
        crate::api::v1::notifications::destroy_notification,
        // Reports
        crate::api::v1::reports::generate_report,
        crate::api::v1::reports::list_reports,
        crate::api::v1::reports::download_report,
        crate::api::v1::reports::delete_report,
        // Events
        crate::api::v1::events::publish_event,
        crate::api::v1::events::process_outbox,
        crate::api::v1::events::get_pending_events,
        crate::api::v1::events::get_dead_letters,
        crate::api::v1::events::retry_dead_letter,
        // Search
        crate::api::v1::search::search,
        crate::api::v1::search::index_document,
        crate::api::v1::search::remove_document,
        crate::api::v1::search::reindex,
        // Tax
        crate::api::v1::tax::create_tax_rate,
        crate::api::v1::tax::list_tax_rates,
        crate::api::v1::tax::get_tax_rate,
        crate::api::v1::tax::update_tax_rate,
        crate::api::v1::tax::get_effective_rate,
        crate::api::v1::tax::calculate_tax,
        crate::api::v1::tax::calculate_invoice_tax,
        crate::api::v1::tax::create_tax_period,
        crate::api::v1::tax::list_tax_periods,
        crate::api::v1::tax::get_tax_period,
        crate::api::v1::tax::calculate_tax_period,
        crate::api::v1::tax::file_tax_period,
        crate::api::v1::tax::delete_tax_rate,
        crate::api::v1::tax::restore_tax_rate,
        crate::api::v1::tax::list_deleted_tax_rates,
        crate::api::v1::tax::destroy_tax_rate,
        crate::api::v1::tax::delete_tax_period,
        crate::api::v1::tax::restore_tax_period,
        crate::api::v1::tax::list_deleted_tax_periods,
        crate::api::v1::tax::destroy_tax_period,
        // Currency
        crate::api::v1::currency::list_currencies,
        crate::api::v1::currency::create_currency,
        crate::api::v1::currency::get_currency,
        crate::api::v1::currency::update_currency,
        crate::api::v1::currency::soft_delete_currency,
        crate::api::v1::currency::restore_currency,
        crate::api::v1::currency::list_deleted_currencies,
        crate::api::v1::currency::destroy_currency,
        crate::api::v1::currency::list_exchange_rates,
        crate::api::v1::currency::create_exchange_rate,
        crate::api::v1::currency::convert_amount,
        crate::api::v1::currency::get_effective_rate,
        crate::api::v1::currency::soft_delete_exchange_rate,
        crate::api::v1::currency::restore_exchange_rate,
        crate::api::v1::currency::list_deleted_exchange_rates,
        crate::api::v1::currency::destroy_exchange_rate,
        // e-Fatura
        crate::api::v1::efatura::create_efatura,
        crate::api::v1::efatura::list_efaturas,
        crate::api::v1::efatura::get_efatura,
        crate::api::v1::efatura::get_efatura_xml,
        crate::api::v1::efatura::send_efatura,
        crate::api::v1::efatura::cancel_efatura,
        crate::api::v1::efatura::check_efatura_status,
        // e-Defter
        crate::api::v1::edefter::create_period,
        crate::api::v1::edefter::list_periods,
        crate::api::v1::edefter::get_period,
        crate::api::v1::edefter::populate_period,
        crate::api::v1::edefter::validate_period,
        crate::api::v1::edefter::generate_yevmiye,
        crate::api::v1::edefter::generate_buyuk_defter,
        crate::api::v1::edefter::sign_berat,
        crate::api::v1::edefter::send_to_saklayici,
        crate::api::v1::edefter::check_status,
    ),
    components(
        schemas(
            // Core
            LoginRequest,
            LoginResponse,
            RefreshTokenRequest,
            RegisterRequest,
            CreateUser,
            UpdateUser,
            UserResponse,
            // MFA
            crate::domain::mfa::model::MfaSetupResponse,
            crate::domain::mfa::model::MfaStatusResponse,
            crate::domain::mfa::model::VerifyTotpRequest,
            crate::domain::mfa::model::DisableMfaRequest,
            crate::domain::mfa::model::VerifyMfaRequest,
            crate::domain::mfa::model::BackupCodesResponse,
            crate::domain::mfa::model::MfaMethod,
            MessageResponse,
            crate::error::ErrorResponse,
            crate::common::PaginationParams,
            // Feature flags
            CreateFeatureFlag,
            UpdateFeatureFlag,
            FeatureFlagResponse,
            FeatureFlagStatus,
            crate::api::v1::feature_flags::FeatureStatusResponse,
            // Jobs
            crate::api::v1::jobs::JobResponse,
            crate::api::v1::jobs::CreateJobRequest,
            crate::api::v1::jobs::FailJobRequest,
            // API Keys
            crate::domain::api_key::model::CreateApiKey,
            crate::domain::api_key::model::UpdateApiKey,
            crate::domain::api_key::model::ApiKeyScope,
            // Notifications
            crate::api::v1::notifications::SendNotificationRequest,
            crate::api::v1::notifications::InAppNotificationResponse,
            crate::api::v1::notifications::UnreadCountResponse,
            crate::api::v1::notifications::MarkReadResponse,
            crate::domain::notification::model::NotificationResponse,
            crate::domain::notification::model::NotificationPreferenceResponse,
            // Reports
            crate::api::v1::reports::GenerateReportRequest,
            crate::api::v1::reports::ReportMetaResponse,
            // Events
            crate::api::v1::events::PublishEventRequest,
            crate::api::v1::events::OutboxEventResponse,
            crate::api::v1::events::DeadLetterResponse,
            crate::api::v1::events::ProcessOutboxResponse,
            // Chart of Accounts
            crate::domain::chart_of_accounts::model::AccountGroup,
            crate::domain::chart_of_accounts::model::ChartAccount,
            crate::domain::chart_of_accounts::model::ChartAccountResponse,
            crate::domain::chart_of_accounts::model::CreateChartAccount,
            crate::domain::chart_of_accounts::model::UpdateChartAccount,
            crate::domain::chart_of_accounts::model::AccountTreeNode,
            crate::domain::chart_of_accounts::model::TrialBalanceEntry,
            // Search
            crate::api::v1::search::SearchRequest,
            crate::api::v1::search::SearchResultResponse,
            crate::api::v1::search::IndexDocumentRequest,
            // Rate Limits
            crate::api::v1::rate_limits::RateLimitDashboardResponse,
            crate::api::v1::rate_limits::RateLimitEntryResponse,
            // Tax
            crate::domain::tax::model::TaxType,
            crate::domain::tax::model::TaxRate,
            crate::domain::tax::model::TaxCalculationResult,
            crate::domain::tax::model::TaxPeriodStatus,
            crate::domain::tax::model::TaxPeriod,
            crate::domain::tax::model::TaxPeriodDetail,
            crate::domain::tax::model::CreateTaxRate,
            crate::domain::tax::model::UpdateTaxRate,
            crate::domain::tax::model::CreateTaxPeriod,
            crate::domain::tax::model::TaxRateResponse,
            crate::domain::tax::model::TaxPeriodResponse,
            crate::api::v1::tax::CalculateTaxRequest,
            crate::api::v1::tax::CalculateInvoiceTaxRequest,
            crate::api::v1::tax::EffectiveRateQuery,
            // Currency
            crate::domain::currency::model::Currency,
            crate::domain::currency::model::CreateCurrency,
            crate::domain::currency::model::UpdateCurrency,
            crate::domain::currency::model::CurrencyResponse,
            crate::domain::currency::model::ExchangeRate,
            crate::domain::currency::model::CreateExchangeRate,
            crate::domain::currency::model::UpdateExchangeRate,
            crate::domain::currency::model::ExchangeRateResponse,
            crate::domain::currency::model::ConversionResult,
            // Goods Receipts
            crate::domain::purchase::model::GoodsReceipt,
            crate::domain::purchase::model::GoodsReceiptResponse,
            crate::domain::purchase::model::CreateGoodsReceipt,
            crate::domain::purchase::model::GoodsReceiptStatus,
            crate::api::v1::goods_receipts::UpdateReceiptStatusRequest,
            // e-Fatura
            crate::domain::efatura::model::EFaturaStatus,
            crate::domain::efatura::model::EFaturaProfile,
            crate::domain::efatura::model::EFaturaResponse,
            crate::domain::efatura::model::CreateEFatura,
            crate::api::v1::efatura::CancelEFaturaRequest,
            // e-Defter
            crate::domain::edefter::model::EDefterStatus,
            crate::domain::edefter::model::LedgerType,
            crate::domain::edefter::model::LedgerPeriod,
            crate::domain::edefter::model::LedgerPeriodResponse,
            crate::domain::edefter::model::CreateLedgerPeriod,
            crate::domain::edefter::model::YevmiyeEntry,
            crate::domain::edefter::model::YevmiyeLine,
            crate::domain::edefter::model::BalanceCheckResult,
            crate::domain::edefter::model::BeratInfo,
            crate::api::v1::edefter::XmlResponse,
            // Webhooks
            crate::domain::webhook::model::WebhookStatus,
            crate::domain::webhook::model::DeliveryStatus,
            crate::domain::webhook::model::CreateWebhook,
            crate::domain::webhook::model::UpdateWebhook,
            crate::domain::webhook::model::WebhookResponse,
            crate::domain::webhook::model::WebhookDeliveryResponse,
        )
    ),
    security(
        ("bearer_auth" = [])
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Admin", description = "Administrative endpoints (rate limits, system status)"),
        (name = "Auth", description = "Authentication endpoints (login, register, token refresh)"),
        (name = "Users", description = "User management endpoints (CRUD operations)"),
        (name = "Tenant", description = "Tenant management and configuration"),
        (name = "Cari", description = "Customer / Vendor accounts"),
        (name = "Stock", description = "Warehouses, stock movements and inventory"),
        (name = "Invoice", description = "Invoices and payments"),
        (name = "Sales", description = "Sales orders and quotations"),
        (name = "Purchase Orders", description = "Purchase orders and vendor management"),
        (name = "Purchase Requests", description = "Purchase requests and approval workflow"),
        (name = "Goods Receipts", description = "Goods receipts for purchase orders"),
        (name = "HR", description = "Employees, attendance, leave and payroll"),
        (name = "Accounting", description = "Chart of accounts and journal entries"),
        (name = "Assets", description = "Fixed assets, depreciation and maintenance"),
        (name = "Project", description = "Projects, WBS and costs"),
        (name = "Manufacturing", description = "Work orders, BOM, routing and quality control"),
        (name = "CRM", description = "Leads, opportunities, campaigns and tickets"),
        (name = "Products", description = "Product catalog, categories and variants"),
        (name = "Chart of Accounts", description = "Chart of accounts, account tree and trial balance"),
        (name = "Feature Flags", description = "Feature flag management endpoints"),
        (name = "Custom Fields", description = "Custom field definitions for dynamic module attributes"),
        (name = "Settings", description = "Configuration management endpoints"),
        (name = "Jobs", description = "Background job scheduler endpoints"),
        (name = "API Keys", description = "API key management and scope validation"),
        (name = "Notifications", description = "In-app notifications, email/SMS sending"),
        (name = "Reports", description = "Report generation and management"),
        (name = "Events", description = "Event bus, outbox pattern, and dead letter queue"),
        (name = "Search", description = "Full-text search across entities"),
        (name = "Tax", description = "Turkish tax rate management, calculation, and KVB period tracking"),
        (name = "Currency", description = "Multi-currency support, exchange rates and conversion"),
        (name = "e-Fatura", description = "Turkish e-Fatura (electronic invoicing) integration with GIB"),
        (name = "e-Defter", description = "Turkish e-Defter (electronic ledger) integration with GIB"),
        (name = "Audit", description = "Audit log retrieval"),
        (name = "Webhooks", description = "Webhook endpoints and delivery management")
    )
)]
pub struct ApiDoc;

/// Security scheme addon for OpenAPI
pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
            );
        }
    }
}
