//! CRM API endpoints (v1)

use actix_web::web;

pub mod campaigns;
pub mod leads;
pub mod opportunities;
pub mod tickets;

/// Configure CRM routes for v1 API
pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/v1/crm/leads")
            .route(web::get().to(leads::get_leads))
            .route(web::post().to(leads::create_lead)),
    )
    .service(
        web::resource("/v1/crm/leads/status/{status}")
            .route(web::get().to(leads::get_leads_by_status)),
    )
    .service(web::resource("/v1/crm/leads/deleted").route(web::get().to(leads::list_deleted_leads)))
    .service(
        web::resource("/v1/crm/leads/{id}")
            .route(web::get().to(leads::get_lead))
            .route(web::delete().to(leads::soft_delete_lead)),
    )
    .service(
        web::resource("/v1/crm/leads/{id}/status").route(web::put().to(leads::update_lead_status)),
    )
    .service(web::resource("/v1/crm/leads/{id}/convert").route(web::post().to(leads::convert_lead)))
    .service(web::resource("/v1/crm/leads/{id}/restore").route(web::put().to(leads::restore_lead)))
    .service(
        web::resource("/v1/crm/leads/{id}/destroy").route(web::delete().to(leads::destroy_lead)),
    )
    .service(
        web::resource("/v1/crm/opportunities")
            .route(web::get().to(opportunities::get_opportunities))
            .route(web::post().to(opportunities::create_opportunity)),
    )
    .service(
        web::resource("/v1/crm/opportunities/status/{status}")
            .route(web::get().to(opportunities::get_opportunities_by_status)),
    )
    .service(
        web::resource("/v1/crm/opportunities/deleted")
            .route(web::get().to(opportunities::list_deleted_opportunities)),
    )
    .service(
        web::resource("/v1/crm/opportunities/{id}")
            .route(web::get().to(opportunities::get_opportunity))
            .route(web::delete().to(opportunities::soft_delete_opportunity)),
    )
    .service(
        web::resource("/v1/crm/opportunities/{id}/status")
            .route(web::put().to(opportunities::update_opportunity_status)),
    )
    .service(
        web::resource("/v1/crm/opportunities/{id}/restore")
            .route(web::put().to(opportunities::restore_opportunity)),
    )
    .service(
        web::resource("/v1/crm/opportunities/{id}/destroy")
            .route(web::delete().to(opportunities::destroy_opportunity)),
    )
    .service(
        web::resource("/v1/crm/pipeline-value")
            .route(web::get().to(opportunities::get_pipeline_value)),
    )
    .service(
        web::resource("/v1/crm/campaigns")
            .route(web::get().to(campaigns::get_campaigns))
            .route(web::post().to(campaigns::create_campaign)),
    )
    .service(
        web::resource("/v1/crm/campaigns/status/{status}")
            .route(web::get().to(campaigns::get_campaigns_by_status)),
    )
    .service(
        web::resource("/v1/crm/campaigns/deleted")
            .route(web::get().to(campaigns::list_deleted_campaigns)),
    )
    .service(
        web::resource("/v1/crm/campaigns/{id}")
            .route(web::get().to(campaigns::get_campaign))
            .route(web::delete().to(campaigns::soft_delete_campaign)),
    )
    .service(
        web::resource("/v1/crm/campaigns/{id}/status")
            .route(web::put().to(campaigns::update_campaign_status)),
    )
    .service(
        web::resource("/v1/crm/campaigns/{id}/restore")
            .route(web::put().to(campaigns::restore_campaign)),
    )
    .service(
        web::resource("/v1/crm/campaigns/{id}/destroy")
            .route(web::delete().to(campaigns::destroy_campaign)),
    )
    .service(
        web::resource("/v1/crm/tickets")
            .route(web::get().to(tickets::get_tickets))
            .route(web::post().to(tickets::create_ticket)),
    )
    .service(
        web::resource("/v1/crm/tickets/status/{status}")
            .route(web::get().to(tickets::get_tickets_by_status)),
    )
    .service(
        web::resource("/v1/crm/tickets/open-count")
            .route(web::get().to(tickets::get_open_tickets_count)),
    )
    .service(
        web::resource("/v1/crm/tickets/deleted")
            .route(web::get().to(tickets::list_deleted_tickets)),
    )
    .service(
        web::resource("/v1/crm/tickets/{id}")
            .route(web::get().to(tickets::get_ticket))
            .route(web::delete().to(tickets::soft_delete_ticket)),
    )
    .service(
        web::resource("/v1/crm/tickets/{id}/status")
            .route(web::put().to(tickets::update_ticket_status)),
    )
    .service(
        web::resource("/v1/crm/tickets/{id}/resolve")
            .route(web::post().to(tickets::resolve_ticket)),
    )
    .service(
        web::resource("/v1/crm/tickets/{id}/restore").route(web::put().to(tickets::restore_ticket)),
    )
    .service(
        web::resource("/v1/crm/tickets/{id}/destroy")
            .route(web::delete().to(tickets::destroy_ticket)),
    );
}
