//! HR (Human Resources) API endpoints (v1)

use actix_web::web;

pub mod attendance;
pub mod employees;
pub mod leave;
pub mod payroll;
pub mod sgk;

/// Configure HR routes for v1 API
pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/v1/hr/employees")
            .route(web::get().to(employees::get_employees))
            .route(web::post().to(employees::create_employee)),
    )
    .service(
        web::resource("/v1/hr/employees/deleted")
            .route(web::get().to(employees::list_deleted_employees)),
    )
    .service(
        web::resource("/v1/hr/employees/{id}")
            .route(web::get().to(employees::get_employee))
            .route(web::delete().to(employees::soft_delete_employee)),
    )
    .service(
        web::resource("/v1/hr/employees/{id}/status")
            .route(web::put().to(employees::update_employee_status)),
    )
    .service(
        web::resource("/v1/hr/employees/{id}/terminate")
            .route(web::post().to(employees::terminate_employee)),
    )
    .service(
        web::resource("/v1/hr/employees/{id}/restore")
            .route(web::put().to(employees::restore_employee)),
    )
    .service(
        web::resource("/v1/hr/employees/{id}/destroy")
            .route(web::delete().to(employees::destroy_employee)),
    )
    .service(
        web::resource("/v1/hr/attendance").route(web::post().to(attendance::record_attendance)),
    )
    .service(
        web::resource("/v1/hr/attendance/employee/{employee_id}")
            .route(web::get().to(attendance::get_attendance_by_employee)),
    )
    .service(
        web::resource("/v1/hr/attendance/deleted")
            .route(web::get().to(attendance::list_deleted_attendance)),
    )
    .service(
        web::resource("/v1/hr/attendance/{id}/soft-delete")
            .route(web::delete().to(attendance::soft_delete_attendance)),
    )
    .service(
        web::resource("/v1/hr/attendance/{id}/restore")
            .route(web::put().to(attendance::restore_attendance)),
    )
    .service(
        web::resource("/v1/hr/attendance/{id}/destroy")
            .route(web::delete().to(attendance::destroy_attendance)),
    )
    .service(
        web::resource("/v1/hr/leave-requests").route(web::post().to(leave::create_leave_request)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/deleted")
            .route(web::get().to(leave::list_deleted_leave_requests)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/employee/{employee_id}")
            .route(web::get().to(leave::get_leave_requests_by_employee)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/{id}/approve")
            .route(web::post().to(leave::approve_leave_request)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/{id}/reject")
            .route(web::post().to(leave::reject_leave_request)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/{id}/soft-delete")
            .route(web::delete().to(leave::soft_delete_leave_request)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/{id}/restore")
            .route(web::put().to(leave::restore_leave_request)),
    )
    .service(
        web::resource("/v1/hr/leave-requests/{id}/destroy")
            .route(web::delete().to(leave::destroy_leave_request)),
    )
    .service(web::resource("/v1/hr/leave-types").route(web::get().to(leave::get_leave_types)))
    .service(
        web::resource("/v1/hr/leave-types/deleted")
            .route(web::get().to(leave::list_deleted_leave_types)),
    )
    .service(
        web::resource("/v1/hr/leave-types/{id}/soft-delete")
            .route(web::delete().to(leave::soft_delete_leave_type)),
    )
    .service(
        web::resource("/v1/hr/leave-types/{id}/restore")
            .route(web::put().to(leave::restore_leave_type)),
    )
    .service(
        web::resource("/v1/hr/leave-types/{id}/destroy")
            .route(web::delete().to(leave::destroy_leave_type)),
    )
    .service(
        web::resource("/v1/hr/payroll/calculate").route(web::post().to(payroll::calculate_payroll)),
    )
    .service(
        web::resource("/v1/hr/payroll/employee/{employee_id}")
            .route(web::get().to(payroll::get_payroll_by_employee)),
    )
    .service(
        web::resource("/v1/hr/payroll/deleted").route(web::get().to(payroll::list_deleted_payroll)),
    )
    .service(
        web::resource("/v1/hr/payroll/{id}/paid").route(web::post().to(payroll::mark_payroll_paid)),
    )
    .service(
        web::resource("/v1/hr/payroll/{id}/soft-delete")
            .route(web::delete().to(payroll::soft_delete_payroll)),
    )
    .service(
        web::resource("/v1/hr/payroll/{id}/restore").route(web::put().to(payroll::restore_payroll)),
    )
    .service(
        web::resource("/v1/hr/payroll/{id}/destroy")
            .route(web::delete().to(payroll::destroy_payroll)),
    )
    // SGK Payroll
    .service(web::resource("/v1/hr/sgk/register").route(web::post().to(sgk::register_sgk_employee)))
    .service(
        web::resource("/v1/hr/sgk/calculate").route(web::post().to(sgk::calculate_sgk_payroll)),
    )
    .service(web::resource("/v1/hr/sgk/bonus").route(web::post().to(sgk::add_bonus)))
    .service(
        web::resource("/v1/hr/sgk/summary/{year}/{month}")
            .route(web::get().to(sgk::get_payroll_summary)),
    )
    .service(
        web::resource("/v1/hr/sgk/ebildirge/{year}/{month}")
            .route(web::get().to(sgk::generate_ebildirge)),
    );
}
