//! Manufacturing API endpoints (v1)

use actix_web::web;

pub mod boms;
pub mod quality_control;
pub mod routings;
pub mod work_orders;

/// Configure manufacturing routes for v1 API
pub fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/v1/manufacturing/work-orders")
            .route(web::get().to(work_orders::get_work_orders))
            .route(web::post().to(work_orders::create_work_order)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/deleted")
            .route(web::get().to(work_orders::list_deleted_work_orders)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{id}")
            .route(web::get().to(work_orders::get_work_order))
            .route(web::delete().to(work_orders::soft_delete_work_order)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{id}/status")
            .route(web::put().to(work_orders::update_work_order_status)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{id}/restore")
            .route(web::put().to(work_orders::restore_work_order)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{id}/destroy")
            .route(web::delete().to(work_orders::destroy_work_order)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{work_order_id}/operations")
            .route(web::get().to(work_orders::get_work_order_operations)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/{work_order_id}/materials")
            .route(web::get().to(work_orders::get_work_order_materials)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/operations")
            .route(web::post().to(work_orders::add_work_order_operation)),
    )
    .service(
        web::resource("/v1/manufacturing/work-orders/materials")
            .route(web::post().to(work_orders::add_work_order_material)),
    )
    .service(web::resource("/v1/manufacturing/boms").route(web::post().to(boms::create_bom)))
    .service(
        web::resource("/v1/manufacturing/boms/deleted")
            .route(web::get().to(boms::list_deleted_boms)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/{id}")
            .route(web::get().to(boms::get_bom))
            .route(web::delete().to(boms::soft_delete_bom)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/{id}/restore")
            .route(web::put().to(boms::restore_bom)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/{id}/destroy")
            .route(web::delete().to(boms::destroy_bom)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/{bom_id}/lines")
            .route(web::get().to(boms::get_bom_lines)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/lines").route(web::post().to(boms::add_bom_line)),
    )
    .service(
        web::resource("/v1/manufacturing/boms/product/{product_id}")
            .route(web::get().to(boms::get_boms_by_product)),
    )
    .service(
        web::resource("/v1/manufacturing/routings").route(web::post().to(routings::create_routing)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/deleted")
            .route(web::get().to(routings::list_deleted_routings)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/{id}")
            .route(web::get().to(routings::get_routing))
            .route(web::delete().to(routings::soft_delete_routing)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/{id}/restore")
            .route(web::put().to(routings::restore_routing)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/{id}/destroy")
            .route(web::delete().to(routings::destroy_routing)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/product/{product_id}")
            .route(web::get().to(routings::get_routings_by_product)),
    )
    .service(
        web::resource("/v1/manufacturing/routings/operations")
            .route(web::post().to(routings::add_routing_operation)),
    )
    .service(
        web::resource("/v1/manufacturing/material-requirements/{product_id}")
            .route(web::get().to(routings::calculate_material_requirements)),
    )
    // Quality Control - Inspections
    .service(
        web::resource("/v1/manufacturing/inspections")
            .route(web::get().to(quality_control::get_inspections))
            .route(web::post().to(quality_control::create_inspection)),
    )
    .service(
        web::resource("/v1/manufacturing/inspections/deleted")
            .route(web::get().to(quality_control::list_deleted_inspections)),
    )
    .service(
        web::resource("/v1/manufacturing/inspections/{id}")
            .route(web::get().to(quality_control::get_inspection))
            .route(web::put().to(quality_control::update_inspection))
            .route(web::delete().to(quality_control::delete_inspection)),
    )
    .service(
        web::resource("/v1/manufacturing/inspections/{id}/restore")
            .route(web::put().to(quality_control::restore_inspection)),
    )
    .service(
        web::resource("/v1/manufacturing/inspections/{id}/destroy")
            .route(web::delete().to(quality_control::destroy_inspection)),
    )
    // Quality Control - NCRs
    .service(
        web::resource("/v1/manufacturing/ncrs")
            .route(web::get().to(quality_control::get_ncrs))
            .route(web::post().to(quality_control::create_ncr)),
    )
    .service(
        web::resource("/v1/manufacturing/ncrs/deleted")
            .route(web::get().to(quality_control::list_deleted_ncrs)),
    )
    .service(
        web::resource("/v1/manufacturing/ncrs/{id}")
            .route(web::get().to(quality_control::get_ncr))
            .route(web::put().to(quality_control::update_ncr))
            .route(web::delete().to(quality_control::delete_ncr)),
    )
    .service(
        web::resource("/v1/manufacturing/ncrs/{id}/restore")
            .route(web::put().to(quality_control::restore_ncr)),
    )
    .service(
        web::resource("/v1/manufacturing/ncrs/{id}/destroy")
            .route(web::delete().to(quality_control::destroy_ncr)),
    );
}
