//! API Version 1

pub mod accounting;
pub mod api_keys;
pub mod archive;
pub mod assets;
pub mod audit;
pub mod auth;
pub mod bank;
pub mod barcode;
pub mod cari;
pub mod chart_of_accounts;
pub mod companies;
pub mod cost_centers;
pub mod crm;
pub mod currency;
pub mod custom_fields;
pub mod customer_portal;
pub mod dashboard;
pub mod documents;
pub mod earchive;
pub mod edefter;
pub mod edefter_blockchain;
pub mod efatura;
pub mod events;
pub mod feature_flags;
pub mod files;
pub mod forecasting;
pub mod goods_receipts;
pub mod graphql;
pub mod hr;
pub mod import;
pub mod invoice;
pub mod ip_whitelist;
pub mod jobs;
pub mod ldap;
pub mod manufacturing;
pub mod mfa;
pub mod notifications;
pub mod observability;
pub mod product_variants;
pub mod project;
pub mod purchase_orders;
pub mod purchase_requests;
pub mod push_notifications;
pub mod rate_limits;
pub mod reports;
pub mod resilience;
pub mod sales;
pub mod search;
pub mod settings;
pub mod shifts;
pub mod stock;
pub mod subscriptions;
pub mod tax;
pub mod tenant;
pub mod users;
pub mod vendor_portal;
pub mod webhooks;
pub mod workflows;

// Explicit re-exports to avoid ambiguity
pub use accounting::configure as accounting_configure;
pub use api_keys::configure as api_keys_configure;
pub use archive::configure as archive_configure;
pub use assets::configure as assets_configure;
pub use audit::configure as audit_configure;
pub use auth::configure as auth_configure;
pub use bank::configure as bank_configure;
pub use barcode::configure as barcode_configure;
pub use cari::configure as cari_configure;
pub use chart_of_accounts::configure as chart_of_accounts_configure;
pub use companies::configure as companies_configure;
pub use cost_centers::configure as cost_centers_configure;
pub use crm::configure as crm_configure;
pub use currency::configure as currency_configure;
pub use custom_fields::configure as custom_fields_configure;
pub use customer_portal::configure as customer_portal_configure;
pub use dashboard::configure as dashboard_configure;
pub use documents::configure as documents_configure;
pub use earchive::configure as earchive_configure;
pub use edefter::configure as edefter_configure;
pub use edefter_blockchain::configure as edefter_blockchain_configure;
pub use efatura::configure as efatura_configure;
pub use events::configure as events_configure;
pub use feature_flags::configure as feature_flags_configure;
pub use files::configure as files_configure;
pub use forecasting::configure as forecasting_configure;
pub use goods_receipts::configure as goods_receipts_configure;
pub use graphql::configure as graphql_configure;
pub use hr::configure as hr_configure;
pub use import::configure as import_configure;
pub use invoice::configure as invoice_configure;
pub use ip_whitelist::configure as ip_whitelist_configure;
pub use jobs::configure as jobs_configure;
pub use ldap::configure as ldap_configure;
pub use manufacturing::configure as manufacturing_configure;
pub use mfa::configure as mfa_configure;
pub use notifications::configure as notifications_configure;
pub use observability::configure as observability_configure;
pub use product_variants::configure as product_variants_configure;
pub use project::configure as project_configure;
pub use purchase_orders::configure as purchase_orders_configure;
pub use purchase_requests::configure as purchase_requests_configure;
pub use push_notifications::configure as push_notifications_configure;
pub use rate_limits::configure as rate_limits_configure;
pub use reports::configure as reports_configure;
pub use resilience::configure as resilience_configure;
pub use sales::configure as sales_configure;
pub use search::configure as search_configure;
pub use settings::configure as settings_configure;
pub use shifts::configure as shifts_configure;
pub use stock::configure as stock_configure;
pub use subscriptions::configure as subscriptions_configure;
pub use tax::configure as tax_configure;
pub use tenant::configure as tenant_configure;
pub use users::configure as users_configure;
pub use vendor_portal::configure as vendor_portal_configure;
pub use webhooks::configure as webhooks_configure;
pub use workflows::configure as workflows_configure;
